### ISSUE TITLE
[BUG]Use Item button made new _OtherHotkey 

### ISSUE THREAD

**Issue by khongtuong** [suriyun-production/mmorpg-kit-docs#1782] opened 2022-11-20 14:04 UTC
Lookat videos below, tested with clean kit:
![image](https://user-images.githubusercontent.com/6816616/202906475-995774e3-6fec-4260-ad58-233eb9727f2f.png)
![image](https://user-images.githubusercontent.com/6816616/202906518-c9fe5d2a-dd0c-40bf-9ad0-af3406d8e08e.png)

`ArgumentNullException: Value cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) (at <c9d3ffd4b98649ee9989e1908eaca019>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].ContainsKey (TKey key) (at <c9d3ffd4b98649ee9989e1908eaca019>:0)
InputManager.HasInputSetting (System.String keyName) (at Assets/UnityMultiplayerARPG/Core/CameraAndInput/Scripts/Input/InputManager.cs:17)
InputManager.IsKeyFromSettingActivated (System.String name, System.Func`2[T,TResult] func) (at Assets/UnityMultiplayerARPG/Core/CameraAndInput/Scripts/Input/InputManager.cs:148)
InputManager.GetButtonDown (System.String name) (at Assets/UnityMultiplayerARPG/Core/CameraAndInput/Scripts/Input/InputManager.cs:226)
MultiplayerARPG.UICharacterHotkey.Update () (at Assets/UnityMultiplayerARPG/Core/Scripts/UI/Hotkey/UICharacterHotkey.cs:101)`

[https://cdn.discordapp.com/attachments/460856634302922763/1043590989975138344/B29C176A-6D57-43BD-884C-6F474D3D5F91.MP4](https://cdn.discordapp.com/attachments/460856634302922763/1043590989975138344/B29C176A-6D57-43BD-884C-6F474D3D5F91.MP4)

**Comment by ljars** [comment] 2022-12-16 00:26
The problem is related to `UICharacterHotkeys.otherHotkey.buttonName` being null. When instantiating the _OtherHotkey GameObject, if you set its `buttonName` field to an empty string instead, the exception doesn't happen.

**Comment by insthync** [comment] 2023-01-17 00:11
Fixed in `1.79b`

**Closed by insthync** 2023-01-17 00:11 UTC

**Comment by shubhank008** [comment] 2023-10-13 20:39
> Fixed in `1.79b`

@insthync would it be possible to link to the exact commit or code change required to fix it ? Facing similar issue when trying to use item on mobile (android device or editor with mobile controls), it fails due to `ArgumentNullException: Value cannot be null. Parameter name: key ` error

**Comment by insthync** [comment] 2023-10-14 06:47
No
