### ISSUE TITLE
jump timing and ability use error

### ISSUE THREAD

**Issue by Niinra** [suriyun-production/mmorpg-kit-docs#2235] opened 2023-08-26 17:20 UTC
when i use an ability while i use the jump a synchronization error happens here is a gif of what happens:
![GIF 26-08-2023 13-07-17](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/5de5cbb6-c62e-4aca-aaee-2a7198c7fe39)

**Comment by insthync** [comment] 2023-08-27 01:55
Your ability animation moving by root motion?

**Comment by Niinra** [comment] 2023-08-30 23:23
No

**Comment by insthync** [comment] 2023-08-31 03:04
Seems like you have to send your project to me again

**Comment by Niinra** [comment] 2023-08-31 15:52
I'll send it right away

**Comment by LordPhrozen** [comment] 2023-09-10 19:22
I'm seeing this too with just basic weapon swings that slow me.

**Comment by LordPhrozen** [comment] 2023-09-18 19:05
@insthync Looks like some difference between server and client side speed calculation, client is trying to slow down, server wants to go at the regular speed. 

Theres also some weirdness going on with "overweight" status caclulation between client /server. Client shows im not overweight, but server says I am. It doesnt look like its taking into consideration the extra weight capacity im granting with the player strength attribute correctly.

Both of these situations end up with what Niinra's video shows

**Comment by insthync** [comment] 2023-09-18 19:28
Did you try a version 1.85?

**Comment by LordPhrozen** [comment] 2023-09-18 20:24
Oh shoot, Didnt see you pushed it! I will check that out and test this week.

**Comment by LordPhrozen** [comment] 2023-09-20 19:24
@insthync 1.85 fixed both the out of sync weight calc, and the leap off and swing slow weapon bugs I saw.
@Niinra Please try 1.85 seems to have a much cleaner sync.

**Comment by LordPhrozen** [comment] 2023-09-22 04:44
@insthync I made some potion items that slow me down ( Item -> Skill ) and I'm experiencing the same issue as Niinra. Looks like the slowdown associated with skill use.

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7896457/f08ab329-b7d9-4f28-a8f9-2015c11042be)
Seems to be miss calculated on either client or server.

**Comment by insthync** [comment] 2023-09-22 06:39
"moveSpeedRateWhileUsingSkill" is move speed rate while casting a  skill, if you want to reduce character movement speed, you have to setup buff -> stats -> move speed

**Comment by LordPhrozen** [comment] 2023-09-22 08:13
@insthync 

The skill is set up correctly, and is working as completely as intended.... unless I'm jump/falling, definitely a bug.
https://imgur.com/5i8pk5k

If I had to guess "moveSpeedRateWhileUsingSkill" is not allowing the player to fall at a normal rate on client side.

And It looks like 1.85 did **not fix** the falling for slow-movement swing weapons either, sorry about that. Here's a good video of it, using the "moveSpeedRateWhileAttacking" property of an item.
https://imgur.com/TjtkAyA

And here's the value set:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7896457/bb8aca5b-5175-425c-9a94-1dbd95e74989)

**Comment by insthync** [comment] 2023-09-22 08:34
So both potion which debuff move speed and move speed rate while doing actions are cause of issues?

**Comment by LordPhrozen** [comment] 2023-09-22 09:45
The potion there is an item(skill). so same problem as Niinra, skill is set to slow the players movement while casting which is intended, but because the player is falling... some weird stuttering happens.

Then the same thing happens with a weapon that has a slow while attacking. if you are falling... theres some strangeness happening between client/server. 

What _should_ happen is the player should fall at normal speed in both of these situations. The imgur links in the previous post are videos of the stuttering that occurs. Having either variable slow the players fall is not ideal.

What I **think** is happening is the server is correctly trying to drop the player at its normal speed, and the client is trying to move slowly. causing the stuttering.

**Comment by LordPhrozen** [comment] 2023-09-22 09:47
To put it simply, if either varible is set to slow the player down some:

moveSpeedRateWhileUsingSkill + falling player = Stuttering/Dsync
moveSpeedRateWhileAttacking + falling player = Stuttering/Dsync

**Comment by insthync** [comment] 2023-09-24 23:12
@Niinra for your case, it is because `doNotChangeVelocityWhileAirborne` is turned on, so it validating by wrong move speed. it must use move speed before airborne and does not have to recalculate move speed. This was fixed, and it will be included in next version (1.85b)

**Closed** 2023-09-24 23:26 UTC
