### ISSUE TITLE
[Bug] quest "complete after talked". The indicator not working properly.

### ISSUE THREAD

**Issue by Espeee** [suriyun-production/mmorpg-kit-docs#1930] opened 2023-02-23 12:21 UTC
![image](https://user-images.githubusercontent.com/93352292/220903950-c8eade19-d431-4d32-845f-0935dbcdb1b5.png)
the indicator is white but it is supposed to be yellow on the npc where i want to talk with.

**Comment by insthync** [comment] 2023-02-28 14:51
It is actually not a bug, I intended to make it work like that.

**Comment by insthync** [comment] 2023-03-02 18:12
Fixed in 1.81

**Closed by insthync** 2023-03-02 18:12 UTC
