### ISSUE TITLE
Pet level/exp wipe after restart

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1756] opened 2022-10-30 22:37 UTC
Many player report that after server restart the pet level/exp is reduced/not saved

I have not checked it yet. Will tomorrow. Just wanted to report it already :)

**Comment by insthync** [comment] 2022-11-10 20:05
How about it now ?

**Comment by moepi2k** [comment] 2022-11-11 11:44
Do you changed something already since 178c? Because it still randon happen that pets level not save or reset after restarting server. But its absolutly random. Some saved some not

**Comment by insthync** [comment] 2022-11-11 13:40
Nothing was changed.

**Comment by moepi2k** [comment] 2022-11-11 16:17
Ok yeah, then the bug should be still in. Pöayer report it everytime after server restart

**Comment by insthync** [comment] 2022-11-11 16:43
When restart all players were leave the game?

**Comment by temelkirci** [comment] 2022-12-08 10:14
@insthync I have the same problem ? How can I solve it ? I am using 1.76v

**Comment by insthync** [comment] 2022-12-08 10:35
Might be because when you closes the servers you close all server before map-server send data to database-management server to save.

**Comment by temelkirci** [comment] 2022-12-08 10:40
What do you suggest to prevent pet level descrease ?

**Comment by temelkirci** [comment] 2022-12-08 10:41
A player sent me message, he say that he had a 30 level pet but now 5 level.How possible ?

**Comment by temelkirci** [comment] 2022-12-08 10:52
I guess we need to send pet level to server database every second, and never let descrease pet level.Somehow pet level decrease, this should never be like that.Please let me know when you have a solution.

**Comment by insthync** [comment] 2022-12-08 11:10
But when you told pet level reduce from 30 to 5, I think the problem might not because of the database, I have a question, when its level/exp wiped, it was summoned or it is still in item form.

**Comment by insthync** [comment] 2022-12-08 11:18
In `charactersummon` table?, I will check the database saving serialization/deserialization.

**Comment by temelkirci** [comment] 2022-12-08 11:40
yes, In charactersummon table.

**Comment by moepi2k** [comment] 2022-12-08 21:34
> server before map-server send data to database-

Hm i dont know. Sometimes player report that theier pets lvl from lvl 10 reduced to lvl 2 after restart. And to take pet to lvl 10 you need multible days in my game.

But i need to check if it happen when its in item form or in spawned form

**Comment by temelkirci** [comment] 2022-12-12 15:23
any solution ?

**Comment by insthync** [comment] 2022-12-12 16:16
Try replace character summon codes to 
```
using LiteNetLib.Utils;
using LiteNetLibManager;
using System.Collections.Generic;

namespace MultiplayerARPG
{
    public enum SummonType : byte
    {
        None,
        Skill,
        PetItem,
        Custom = byte.MaxValue
    }

    [System.Serializable]
    public class CharacterSummon : INetSerializable
    {
        public static readonly CharacterSummon Empty = new CharacterSummon();
        public string id;
        public SummonType type;
        public int dataId;
        public float summonRemainsDuration;
        public uint objectId;
        public short level;
        public int exp;
        public int currentHp;
        public int currentMp;
        // Properties for save / load
        public short Level { get { return CacheEntity != null ? CacheEntity.Level : level; } }
        public int Exp { get { return CacheEntity != null ? CacheEntity.Exp : exp; } }
        public int CurrentHp { get { return CacheEntity != null ? CacheEntity.CurrentHp : currentHp; } }
        public int CurrentMp { get { return CacheEntity != null ? CacheEntity.CurrentMp : currentMp; } }

        [System.NonSerialized]
        private SummonType dirtyType;
        [System.NonSerialized]
        private int dirtyDataId;
        [System.NonSerialized]
        private short dirtyLevel;

        [System.NonSerialized]
        private BaseSkill cacheSkill;
        [System.NonSerialized]
        private BaseItem cachePetItem;
        [System.NonSerialized]
        private BaseMonsterCharacterEntity cachePrefab;
        [System.NonSerialized]
        private CalculatedBuff cacheBuff;

        [System.NonSerialized]
        private BaseMonsterCharacterEntity cacheEntity;
        public BaseMonsterCharacterEntity CacheEntity
        {
            get
            {
                if (cacheEntity == null && objectId > 0)
                    BaseGameNetworkManager.Singleton.Assets.TryGetSpawnedObject(objectId, out cacheEntity);
                return cacheEntity;
            }
        }

        private void MakeCache()
        {
            if (dirtyType != type || dirtyDataId != dataId || dirtyLevel != level)
            {
                dirtyType = type;
                dirtyDataId = dataId;
                dirtyType = type;
                dirtyLevel = level;
                cacheSkill = null;
                cachePetItem = null;
                cachePrefab = null;
                Buff tempBuff = Buff.Empty;
                switch (type)
                {
                    case SummonType.Skill:
                        if (GameInstance.Skills.TryGetValue(dataId, out cacheSkill))
                            cachePrefab = cacheSkill.Summon.MonsterEntity;
                        break;
                    case SummonType.PetItem:
                        if (GameInstance.Items.TryGetValue(dataId, out cachePetItem) && cachePetItem is IPetItem)
                            cachePrefab = (cachePetItem as IPetItem).PetEntity;
                        break;
                    case SummonType.Custom:
                        cachePrefab = GameInstance.CustomSummonManager.GetPrefab(dataId);
                        break;
                }
                if (cachePrefab != null && cachePrefab.CharacterDatabase != null)
                    tempBuff = cachePrefab.CharacterDatabase.SummonerBuff;
                cacheBuff = new CalculatedBuff(tempBuff, level);
            }
        }

        public void Summon(BaseCharacterEntity summoner, short summonLevel, float duration)
        {
            if (GetPrefab() == null)
                return;

            LiteNetLibIdentity spawnObj = BaseGameNetworkManager.Singleton.Assets.GetObjectInstance(
                GetPrefab().Identity.HashAssetId,
                GameInstance.Singleton.GameplayRule.GetSummonPosition(summoner),
                GameInstance.Singleton.GameplayRule.GetSummonRotation(summoner));
            cacheEntity = spawnObj.GetComponent<BaseMonsterCharacterEntity>();
            BaseGameNetworkManager.Singleton.Assets.NetworkSpawn(spawnObj);
            CacheEntity.Summon(summoner, type, summonLevel);
            objectId = CacheEntity.ObjectId;
            summonRemainsDuration = duration;
            level = summonLevel;
        }

        public void Summon(BaseCharacterEntity summoner, short summonLevel, float duration, int summonExp)
        {
            Summon(summoner, summonLevel, duration);
            CacheEntity.Exp = summonExp;
            exp = summonExp;
        }

        public void Summon(BaseCharacterEntity summoner, short summonLevel, float duration, int summonExp, int summonCurrentHp, int summonCurrentMp)
        {
            Summon(summoner, summonLevel, duration, summonExp);
            CacheEntity.CurrentHp = summonCurrentHp;
            CacheEntity.CurrentMp = summonCurrentMp;
            currentHp = summonCurrentHp;
            currentMp = summonCurrentMp;

        }

        public void UnSummon(BaseCharacterEntity summoner)
        {
            switch (type)
            {
                case SummonType.PetItem:
                    // Return to character as a pet item
                    CharacterItem newItem = CharacterItem.Create(dataId, Level, 1);
                    newItem.exp = Exp;
                    newItem.Lock(CurrentHp <= 0 ?
                        GameInstance.Singleton.petDeadLockDuration :
                        GameInstance.Singleton.petUnSummonLockDuration);
                    summoner.AddOrSetNonEquipItems(newItem);
                    break;
                case SummonType.Custom:
                    GameInstance.CustomSummonManager.UnSummon(this);
                    break;
            }

            if (CacheEntity)
                CacheEntity.UnSummon();
        }

        public BaseSkill GetSkill()
        {
            MakeCache();
            return cacheSkill;
        }

        public BaseItem GetPetItem()
        {
            MakeCache();
            return cachePetItem;
        }

        public BaseMonsterCharacterEntity GetPrefab()
        {
            MakeCache();
            return cachePrefab;
        }

        public CalculatedBuff GetBuff()
        {
            MakeCache();
            return cacheBuff;
        }

        public bool ShouldRemove()
        {
            return (CacheEntity && CacheEntity.CurrentHp <= 0) || (type == SummonType.Skill && summonRemainsDuration <= 0f);
        }

        public void Update(float deltaTime)
        {
            switch (type)
            {
                case SummonType.Skill:
                    // Update remains duration when it reached 0 it will be unsummoned
                    summonRemainsDuration -= deltaTime;
                    break;
            }
            // Makes update in main thread to collects data to use in other threads (save to database thread)
            level = Level;
            exp = Exp;
            currentHp = CurrentHp;
            currentMp = CurrentMp;
        }

        public CharacterSummon Clone(bool generateNewId = false)
        {
            return new CharacterSummon()
            {
                id = generateNewId ? GenericUtils.GetUniqueId() : id,
                type = type,
                dataId = dataId,
                summonRemainsDuration = summonRemainsDuration,
                objectId = objectId,
                level = level,
                exp = exp,
                currentHp = currentHp,
                currentMp = currentMp,
            };
        }

        public static CharacterSummon Create(SummonType type, int dataId)
        {
            return new CharacterSummon()
            {
                id = GenericUtils.GetUniqueId(),
                type = type,
                dataId = dataId,
            };
        }

        public void Serialize(NetDataWriter writer)
        {
            writer.Put(id);
            writer.Put((byte)type);
            if (type != SummonType.None)
            {
                writer.PutPackedInt(dataId);
                switch (type)
                {
                    case SummonType.Skill:
                        writer.Put(summonRemainsDuration);
                        break;
                }
                writer.PutPackedUInt(objectId);
                writer.PutPackedShort(level);
                writer.PutPackedInt(exp);
                writer.PutPackedInt(currentHp);
                writer.PutPackedInt(currentMp);
            }
        }

        public void Deserialize(NetDataReader reader)
        {
            id = reader.GetString();
            type = (SummonType)reader.GetByte();
            if (type != SummonType.None)
            {
                dataId = reader.GetPackedInt();
                switch (type)
                {
                    case SummonType.Skill:
                        summonRemainsDuration = reader.GetFloat();
                        break;
                }
                objectId = reader.GetPackedUInt();
                level = reader.GetPackedShort();
                exp = reader.GetPackedInt();
                currentHp = reader.GetPackedInt();
                currentMp = reader.GetPackedInt();
            }
        }
    }

    [System.Serializable]
    public class SyncListCharacterSummon : LiteNetLibSyncList<CharacterSummon>
    {
        protected override CharacterSummon DeserializeValueForSetOrDirty(int index, NetDataReader reader)
        {
            CharacterSummon result = this[index];
            result.summonRemainsDuration = reader.GetFloat();
            result.objectId = reader.GetPackedUInt();
            return result;
        }

        protected override void SerializeValueForSetOrDirty(int index, NetDataWriter writer, CharacterSummon value)
        {
            writer.Put(value.summonRemainsDuration);
            writer.PutPackedUInt(value.objectId);
        }
    }
}

```

**Comment by temelkirci** [comment] 2022-12-12 17:17
![Ekran Alıntısı](https://user-images.githubusercontent.com/11313412/207110447-dbee45d0-743e-43e4-a9e6-8ba871a70860.PNG)

I am using v1.76d2

which codes should I add ?

**Comment by insthync** [comment] 2022-12-12 17:30
![Screenshot_220](https://user-images.githubusercontent.com/2697550/207113484-e537ce9c-07f7-4658-ba53-3b9fc0beff12.png)

**Comment by temelkirci** [comment] 2022-12-12 17:36
Thank you.I will let you know the result at the weekend.

**Comment by temelkirci** [comment] 2022-12-14 09:35
not working :( still same problem.

Players report that their pets decrease level suddenly or warp to another map. 

Any other solution ?

**Comment by insthync** [comment] 2022-12-14 11:52
Don't ask for solution while I try to find it.

**Comment by moepi2k** [comment] 2022-12-14 20:54
> not working :( still same problem.
> 
> Players report that their pets decrease level suddenly or warp to another map.
> 
> Any other solution ?

what yoou mean with "warp to another map"? i just talk to my players and following some ideas of the player what it could be. but since its realy rare its hard to find it

-> It's most probable, since all pet resets that I've ecountered happend while leaving/entering another zone, esp town
-> I think it's due to going to far from your pet that causes him to tp to player right when he's exit area
That's why I always uneq my pet before changing area
->There are different theories, I'm pretty sure if you have more than one pet in the same location (i.e, chest, inventory ect) it links the pets lvls and bugs them so they reset and can't lvl anymore. I make sure I don't have more than 1 pet on me or in 1 chest at any given time, I havnt been hit by the bug since I started doing that.

**Comment by insthync** [comment] 2022-12-20 03:32
The level/exp wiped should be fixed by the codes I posted here, but I don't know how it reducing from 30 to 2 as you said yet.


You may try deleting 2 functions codes (which were made for optimization propose) like this

![Screenshot_271](https://user-images.githubusercontent.com/2697550/208576807-9e8a7377-6459-4005-9c45-fc256e8d0c66.png)

**Comment by temelkirci** [comment] 2022-12-20 07:19
@insthync Thak you.I hope this will fix it.I will update my client and server and let you know the results in a few days.

**Comment by temelkirci** [comment] 2022-12-22 13:46
@moepi2k  @insthync  Problem looks solved.Thank you

**Comment by moepi2k** [comment] 2022-12-24 20:12
☹️

**Comment by insthync** [comment] 2022-12-25 00:57
Ask to make sure, is it decreased or reset?

Decrease is 30 to 2
Reset is 30 to 0

**Comment by temelkirci** [comment] 2022-12-25 09:27
Decrease 50 to 10.No reset

**Comment by moepi2k** [comment] 2022-12-25 20:22
My player reported both, decrease and reset. But hard to say if its really a reset because if its set from 30 to 2 why it not happen from 30 to 1

**Comment by temelkirci** [comment] 2022-12-30 07:58
@moepi2k  unsummon pet before teleport is not working in your game?

**Comment by moepi2k** [comment] 2022-12-30 09:03
What you mean with not working? You can unsummon everywhere. But i dont know if level/xp decrease happen when pet is summoned or also in item form.

**Comment by temelkirci** [comment] 2022-12-30 17:14
![Ekran görüntüsü 2022-12-30 201142](https://user-images.githubusercontent.com/11313412/210096036-d00a293a-9191-4cc3-8c93-7fd88485e6f7.png)


I added some debug.log in CharacterSummon.cs    My pet level is 14 but seems 60 while teleporting another map via NPC.

**Comment by insthync** [comment] 2022-12-31 01:31
Please copy-paste your CharacterSummon.cs codes here, I want to see it.

**Comment by insthync** [comment] 2022-12-31 03:31
Try make changes following this:

https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/dd8fe6d56d1d47ccce869a6b254c5543b92aca4b

**Comment by insthync** [comment] 2023-01-04 17:08
In case you may doubt how it will fix the issues, 

You must know first that it will use `objectId` in `CharacterSummon` to find and cache a reference to the monster entity (`CacheEntity`), the `Level`  property will bring the level from `CacheEntity`, not the one which stored to `CharacterSummon` (`level` field).

Then the `objectId` will be synced to clients so clients can use it to find the monster entity and may be used for UI displaying purposes.

The problem is, it will be synced to the database management server too for caching, then when client enters the game, it will load data from the database management server, and the database management server will bring data from the cache first (if it has not existed from the cache it will load from database), then when map-server receive data from the database management server it will get `objectId` too, and it will find `CacheEntity` by `objectId` and use `level` from `CacheEntity`, not `level` from `CharacterSummon`, so to change to use `CharacterSummon`'s `level` can fix wrong summon level issues.

**Comment by insthync** [comment] 2024-10-24 19:55
@moepi2k Occurring when the pet dead or something?

**Comment by moepi2k** [comment] 2024-10-24 21:48
maybe, players told me it can happen when same pets of same type are in inventory

**Comment by insthync** [comment] 2024-10-26 10:00
You said
```
btw just was able to reproduce pet level reseting. sometimes when u have a pet with specific level in inventory and u add another pet of the same type it will reset. in my case i added it with /add_item PET
```

But I cannot reproduce, capture the reproducing video.

**Comment by moepi2k** [comment] 2024-10-26 12:10
i was only able once to reproduce. same as a player told me. when i have a pet in my inventory e.g level 5 and pickup another pet with level 1 moveing around inventory or so it can lead to reset. it happen rarely but it happen

**Comment by insthync** [comment] 2024-10-26 13:27
Reopened here https://github.com/suriyun-production/mmorpg-kit-docs/issues/2593

**Closed by insthync** 2024-10-26 13:27 UTC
