### ISSUE TITLE
Rotation Issue 1.76D2

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#1693] opened 2022-09-07 17:59 UTC
https://user-images.githubusercontent.com/7702658/188946857-6111bfe2-ec2d-418f-a6bc-83850b5a07e1.mp4

Ive updated today to the 1.76D2 version and notice my rotation is really bad.. 
its like it only updates rotation after x amount of time instead of lerping it or smooth..

**Comment by Callepo** [comment] 2022-09-07 19:11
So i realised that on my other scenes, the rotation works fine as intended.
But just on this 1 particular map that has alot of building entities, the rotation seems to be dragging behind..
While the position is still Sync properly..

So its a packet issue i think, if u have to much entities on 1 map.. the rotation is gone..
This wasnt a problem before i updated to the latest version. i was running 1.76 before

**Comment by insthync** [comment] 2022-09-07 22:00
1.76 don't have this problem, you just update from 1.76 to 1.76d2, not b or c to d, right? so I can scope down what can be the cause of the problem

**Comment by Callepo** [comment] 2022-09-07 22:04
1.76
Vehicles and players rotation were jumping around and turning when u stop moving. but when ur moving it updates fine..

I updated to 1.76D2 directly. Now the issue in 1.76 is gone.. and all looks good..

But i have a map server with alot of Entities on it.. 
The player moves around fine 0 lag.. but rotation is very bad as seen in the video..

I go to other map where not many entities.. All work perfectly again..

SO the rotation is effected by the amount of entities on the mapserver.. but somehow not the position of the player.. 
Shouldnt position and rotation be updating same time? or together

**Comment by Callepo** [comment] 2022-09-07 22:19
@insthync i can make a better video and show you, or u can log into the game and check ? 
what do u prefer?

**Comment by insthync** [comment] 2022-09-08 03:29
You can send link for your game to email ittipon.bay@gmail.com

**Comment by Callepo** [comment] 2022-09-08 03:36
> ittipon.bay@gmail.com

Done..

You need 2 people to be online to test it.

Locally your character rotates fine..
But others see u really bad… 

Let me know when u will login and ill come help.

**Comment by insthync** [comment] 2022-09-13 09:10
Fixed in 1.77

**Closed by insthync** 2022-09-13 09:10 UTC
