### ISSUE TITLE
Animation Issue

### ISSUE THREAD

**Issue by temelkirci** [suriyun-production/mmorpg-kit-docs#2308] opened 2023-11-18 03:47 UTC
All mobs which has 4 legs like bear,lion,tiger have this issue.I update animations on server side.Somethimes works well while walking around, but sometimes do not work very well.Any idea ?

![Screenshot_20231117_010651](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/ec082763-8fe8-47f9-a207-472cc7e3b743)
![Screenshot_20231117_010028](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/7776849f-55ec-49a5-94be-911892b7ae74)
![Screenshot_20231117_010445](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/04b31404-f021-4549-938c-7fed7af6d670)

**Comment by insthync** [comment] 2023-11-18 04:05
For an animations, you won't have to check at the server-side, not sure the problem is tiger standup like human?

**Comment by temelkirci** [comment] 2023-11-18 04:07
the problem is tiger standup like human

**Comment by temelkirci** [comment] 2023-11-18 04:10
and vice versa

**Comment by Niinra** [comment] 2023-11-19 19:11
I think this is a problem with the configuration of your mob, it cannot be the asset that causes this error, check that your mobs have their own avatar definition and are generic
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/019a31ce-2a4a-4234-b285-dda66f3f8989)
and:
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/115952096/b63f58f4-38d2-496c-af8b-5c72d0656633)

**Comment by Niinra** [comment] 2023-11-24 06:32
You can share photos of how you have your animation configuration and general behavior for video

**Comment by insthync** [comment] 2023-12-14 06:39
@temelkirci I never saw anything like this, don't know how to fix it, I want to see your character's rig setting it should be generic for non-humanoid animation, let's start from that.

**Comment by insthync** [comment] 2024-02-02 07:47
No answer, I will close it, you can reopen it if you still need my help :)

**Closed by insthync** 2024-02-02 07:47 UTC
