### ISSUE TITLE
Monster Spawns Bug

### ISSUE THREAD

**Issue by AsheshPlays** [suriyun-production/mmorpg-kit-docs#2103] opened 2023-05-26 14:59 UTC
After a few hours from when the server started, when players start to kill monster, there are spawns that don't respawn anymore. 

![Screenshot_20230526_210615_GenesisM.jpg](https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/fd4cf458-2e9e-492d-b298-d6e101e96871)

![Screenshot_20230526_210547_GenesisM.jpg](https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/58c8b3a4-be9d-4993-8440-a788afa41ef2)

![Screenshot_20230526_210533_GenesisM.jpg](https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/ebb1e386-6913-4363-8e4a-5dcfd5b1407c)

Is there something i should set? The only fix i do is restart the server.

**Comment by insthync** [comment] 2023-05-27 00:45
Try debug RespawnRoutine function.

**Comment by AsheshPlays** [comment] 2023-05-27 16:55
@insthync where or how can i do this?

**Comment by AsheshPlays** [comment] 2023-05-27 19:14
@insthync I tried restarting the server then adjusting all the spawns. Still the problem occurs when a spawn is being farmed or being killed for a period of time. They get bugged one by one until the whole spawn don't respawn anymore and stays dead on the ground. This is a screenshot sent to me by a player. 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/f981cfdd-14c7-4242-9030-bc5959328a55)

**Comment by insthync** [comment] 2023-05-27 19:53
Find RespawnRoutine by ide, visual studio or something, then debug by write some log message to check that is it work properly or not.

**Comment by AsheshPlays** [comment] 2023-05-27 22:58
@insthync is this correct?

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/98a3fcbb-e544-4f6c-b36c-24f9f649288f)

**Comment by insthync** [comment] 2023-05-28 02:25
Yes, do something like that

**Comment by AsheshPlays** [comment] 2023-05-28 09:19
Ive been observing it for few hours until monsters became buggy again and dont respawn but I never seen the debug message. Here is the complete log anyway. 

[Log_Database_Central_MapSpawn.err.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/11584166/Log_Database_Central_MapSpawn.err.log)
[Log_Database_Central_MapSpawn.info.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/11584167/Log_Database_Central_MapSpawn.info.log)
[Log_Database_Central_MapSpawn.warn.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/11584168/Log_Database_Central_MapSpawn.warn.log)
[Log_Map(Z01) Instance().err.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/11584169/Log_Map.Z01.Instance.err.log)
[Log_Map(Z01) Instance().info.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/11584171/Log_Map.Z01.Instance.info.log)
[Log_Map(Z01) Instance().warn.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/11584172/Log_Map.Z01.Instance.warn.log)
[Log_Map(Z24) Instance().err.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/11584173/Log_Map.Z24.Instance.err.log)
[Log_Map(Z24) Instance().info.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/11584174/Log_Map.Z24.Instance.info.log)
[Log_Map(Z24) Instance().warn.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/11584175/Log_Map.Z24.Instance.warn.log)

**Comment by tubhluas** [comment] 2023-06-01 15:23
I have that issue however I over come that by changing the entity lite net lib pooling size to 1 or 2. For some reason if the numbers too high it will cause that issue after it respawn once or twice.

**Comment by insthync** [comment] 2023-06-01 16:03
@AsheshPlays Change from Debug.Log to Logging.Log and add more places to write debug messages, I see nothing from your logs, didn't you read it?, if you read it already you will see it has nothing.

**Comment by insthync** [comment] 2023-06-02 08:23
@AsheshPlays How about pooling size?

**Comment by insthync** [comment] 2023-06-02 08:40
@AsheshPlays That character is placed on scene or spawned by spawn area?

**Comment by insthync** [comment] 2023-06-02 11:39
Try add onGetInstance event like this to `BaseMonsterCharacterEntity`:
```
        protected override void EntityAwake()
        {
            base.EntityAwake();
            gameObject.tag = CurrentGameInstance.monsterTag;
            gameObject.layer = CurrentGameInstance.monsterLayer;
            Identity.onGetInstance.AddListener(InitStats);
        }

        protected override void EntityOnDestroy()
        {
            base.EntityOnDestroy();
            Identity.onGetInstance.RemoveListener(InitStats);
        }
```

**Comment by AsheshPlays** [comment] 2023-06-02 13:07
@insthync
I placed them by spawn area.

**Comment by insthync** [comment] 2023-06-05 19:12
Fixed in 1.83f

**Comment by temelkirci** [comment] 2023-06-10 20:54
> @insthync I placed them by spawn area.

your issue was solved with this ?

**Comment by AsheshPlays** [comment] 2023-06-10 20:58
@temelkirci
Same but I added a temporary script attached to mobs that refreshes the monsters with a given specific time intervals. Its a temporary solution.

**Comment by insthync** [comment] 2023-06-10 21:05
@AsheshPlays Why the fuck did you don't tell me?

**Comment by AsheshPlays** [comment] 2023-06-10 21:09
@insthync
sorry, i just have so much in my head currently and forgot to tell it. it was noted on my to-do list. im just pre-occupied with the faction and quest creations lately. sorry. but its lesser now

**Comment by AsheshPlays** [comment] 2023-06-10 21:10
@insthync
sorry, i just have so much in my head currently and forgot to tell it. it was noted on my to-do list. im just pre-occupied with the faction and quest creations lately. sorry. but its lesser now

**Comment by AsheshPlays** [comment] 2023-06-10 21:11
@insthync
Also i havent updated to latest version yet. i only did what you wrote above.

**Comment by insthync** [comment] 2023-06-10 21:12
Okay, so you didn't update to the latest version yet. Hmm, then it can't be determined that it is not working.

**Comment by AsheshPlays** [comment] 2023-06-10 21:18
@insthync

This is recorded just now. Server started yesterday and only a few had problems unlike before.https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/defabe76-75d7-467e-b3de-da37772ef6c6

**Comment by AsheshPlays** [comment] 2023-06-10 21:20
@insthync

i will update later and will give my feedback here after a few hours of monitoring.

**Comment by AsheshPlays** [comment] 2023-06-10 22:05
@insthync
So before I update the kit, I recorded this video to show the monsters that are "sleeping" as my testers say. Actually there are 2 issues here but for this post, its the first half of the video.

https://youtu.be/IMUN1VMlvus

**Comment by temelkirci** [comment] 2023-06-12 16:22
@insthync @AsheshPlays This issue was solved by 1.83g2. Thanks

**Comment by AsheshPlays** [comment] 2023-06-12 16:25
@temelkirci
im currently not home so idk yet. If yours is fixed, idk mine yet.. your map is very simple and almost plain so its not that hard while my map has hundreds if trees and plateaus and hiils and mounds. I will update on this still..

**Comment by temelkirci** [comment] 2023-06-13 07:28
![image_074_0000](https://github.com/suriyun-production/mmorpg-kit-docs/assets/11313412/1928bf1e-e29b-40d1-a470-f955bf757228)

Unfortunaly I am still having same issue :(

[Log_Map(City) Instance().info.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/11731857/Log_Map.City.Instance.info.log)

[Log_Map(City) Instance().warn.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/11731858/Log_Map.City.Instance.warn.log)

[Log_Database_Central_MapSpawn.err.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/11731859/Log_Database_Central_MapSpawn.err.log)
 
[Log_Database_Central_MapSpawn.info.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/11731853/Log_Database_Central_MapSpawn.info.log)
[Log_Database_Central_MapSpawn.warn.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/11731854/Log_Database_Central_MapSpawn.warn.log)
[Log_Map(City) Instance().err.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/11731855/Log_Map.City.Instance.err.log)

**Comment by AsheshPlays** [comment] 2023-06-13 07:34
@temelkirci
that's what i was try to say to you.. suri added the patch and few hours after you said its fixed without doing a monitoring.. it needs atleast a day.. i have maps that have 800-1000 mobs, some maps fewer..

**Comment by insthync** [comment] 2023-06-13 07:50
@AsheshPlays You have to update because I did a lots more than I posted here.

**Comment by temelkirci** [comment] 2023-06-13 08:07
@insthync Results are better for me.I have 600 mobs each map.I checked 2 maps and almost 10-15 monsters on ground in 1 day.Better but somethings still wrong for me.

**Comment by temelkirci** [comment] 2023-06-16 08:24
> I have that issue however I over come that by changing the entity lite net lib pooling size to 1 or 2. For some reason if the numbers too high it will cause that issue after it respawn once or twice.

@tubhluas Pls can you tell me How can I do that ?

**Comment by insthync** [comment] 2023-07-11 17:02
It should have adjusting needed, it should work properly on any settings, I will try to fix it.

**Comment by AsheshPlays** [comment] 2023-07-11 20:24
@insthync

It often happens on spots where players stay there and just farm.. As time goes by, later on, mob on that spot start to have problems..

**Comment by insthync** [comment] 2023-08-01 21:43
I cannot reproduce it yet, want to see your monster destroy, respawn delay settings, and I have a question how those monsters that have this problem spawned.

**Comment by AsheshPlays** [comment] 2023-08-02 17:41
What do i need to send you? The monster setup?

**Comment by insthync** [comment] 2023-08-02 18:01
Yes `monster destroy, respawn delay settings` `how those monsters spawned`

**Comment by insthync** [comment] 2023-08-06 15:58
When I will know it?

**Comment by AsheshPlays** [comment] 2023-08-06 16:51
@insthync 

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/c257d1a6-4501-4d4b-81e1-7d1dbab8b00d)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/62997243-9fc6-4679-94f4-6a68e48f8057)

![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/118698151/f5427340-b206-4018-bb68-8522d08cc139)

**Comment by insthync** [comment] 2023-08-08 16:08
I really can't reproduce it

**Comment by AsheshPlays** [comment] 2023-08-08 16:57
What do you advice sir?

**Comment by insthync** [comment] 2023-08-08 21:59
[MMORPG_KIT-DebugMonsterDeath.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/12296355/MMORPG_KIT-DebugMonsterDeath.zip)

Import this package, then rebuild, after that test until the problem occurred, and finally send the log files to me.

**Comment by insthync** [comment] 2023-08-13 03:19
How is the debugging ?

You may try change codes in `DamageableEntityExtensions` to be

```
namespace MultiplayerARPG
{
    public static class DamageableEntityExtensions
    {
        public static bool IsDead(this IDamageableEntity damageableEntity)
        {
            return damageableEntity.IsNull() || damageableEntity.CurrentHp <= 0;
        }

        public static bool IsHideOrDead(this IDamageableEntity damageableEntity)
        {
            return damageableEntity.IsDead() || damageableEntity.IsHide();
        }
    }
}

```

as it has another customer found the same bug, with a null error, so I add null checking before checking its HP.

**Comment by insthync** [comment] 2023-08-13 14:45
In `BaseMonsterCharacterEntity` add `try...catch` to `GivingRewardToKillers()` like this to prevent errors which can break the function.

![Screenshot_784](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/23f7fa77-85b1-48b9-8b6a-6aff36c60702)

**Comment by AsheshPlays** [comment] 2023-08-14 22:53
@insthync

I redid all my monsters and will be conducting a public stress test later.. in few hours maybe.. Ill be having the results by the end of the day. The error i get right now is saying "NO TAG something " but my monsters have TAGs.

**Comment by AsheshPlays** [comment] 2023-08-14 22:55
@insthync

I will try changing the code first before testing it for public too. Thanks for that and I will be monitoring it.. Because it only happens if lots of players are farming on one spot with similar monsters.

**Comment by insthync** [comment] 2023-08-15 02:02
> @insthync
> 
> I redid all my monsters and will be conducting a public stress test later.. in few hours maybe.. Ill be having the results by the end of the day. The error i get right now is saying "NO TAG something " but my monsters have TAGs.

It is a tag for logging, not a monster tag, don't worry about it.

**Closed** 2023-09-09 16:16 UTC
