### ISSUE TITLE
treasure/loot Containers

### ISSUE THREAD

**Issue by aggaton** [suriyun-production/mmorpg-kit-docs#1166] opened 2021-10-02 19:14 UTC
I am looking for a tutorial or example on how to add treasure/loot containers also adding doors that can be opened/closed. I am planning to add adventure aspects to my game, by placing various clues inside containers like, drawers, chests or dead people, so I am trying to figure out ways to do this within the framework of the kit. So far all I have been able to find is the storage chest that is part of the building features, however it is unclear how to change the look and feel of the chest and how to place things inside script-wise. I have also been looking into the lootbag addon since it seems to contain elements of what I am looking for, unfortunately that addon seem to crash the game, so I have unable to see it in action.

**Comment by aggaton** [comment] 2021-10-03 04:10
Never mind I figured out how to do it using the lootbag addon with some minor code changes turning a monster entity into a chest. If you are considering incorporating the lootbag addon into the main code base, please consider my changes as well and maybe make a separate inanimate object class for these things https://github.com/aggaton/lootbag_with_treasure_loot, in order to cut down on needed components.

**Comment by gordowebdesign** [comment] 2021-10-13 03:59
This is not a bug, you should post on discord...

**Comment by insthync** [comment] 2021-11-14 16:27
In 1.71b, it has a `ItemsContainerEntity` which  I use it as character corpse.

- Add `playerCorpsePrefab` setting to `GameInstance`, it is prefab for player corpse which will be instantiate when player character dying (corpses will instantiating while `playerDeadDropItemMode` set to `Corpse Looting`).
- Add `playerDeadDropItemMode` setting to `GameInstance`. If it is `Drop On Ground`, it will drops items on ground. If it is `Corpse Looting`, it will instantiates corpse with dropping items inside.
- Add `monsterCorpsePrefab` setting to `GameInstance`, it is prefab for monster corpse which will be instantiate when monster character dying (corpses will instantiating while `monsterDeadDropItemMode` set to `Corpse Looting`).
- Add `monsterDeadDropItemMode` setting to `GameInstance`. If it is `Drop On Ground`, it will drops items on ground. If it is `Corpse Looting`, it will instantiates corpse with dropping items inside.
- Add `playerDeadDropsEquipWeapons` setting to map info, it this is `TRUE`, player who dies while staying on the map will drops equipped weapons.
- Add `playerDeadDropsEquipItems` setting to map info, it this is `TRUE`, player who dies while staying on the map will drops equipped items.
- Add `playerDeadDropsNonEquipItems` setting to map info, it this is `TRUE`, player who dies while staying on the map will drops non-equipped items.

You can override `ItemsContainerEntity` to add randoming items.

**Closed by insthync** 2021-11-14 16:27 UTC
