### ISSUE TITLE
Warehouse bug

### ISSUE THREAD

**Issue by BarzoStrike** [suriyun-production/mmorpg-kit-docs#1740] opened 2022-10-20 20:19 UTC
When the warehouse and guild move items to the warehouse, the items are lost. Lost items are not in the player's inventory. These items will be lost while using mysql, if you use sqlite, the items will be duplicated.

I am using mysql server Most of the players on my server reported that their items were lost

how to trigger
if you take action at the time you shut down the server.
sometimes the server swallows old items

https://www.youtube.com/watch?v=XLEHCLlvI7A

**Comment by moepi2k** [comment] 2022-10-20 22:23
i dont know if its related, but my player also report many times that items are lost on personal bank, i dont know how to reproduce

**Comment by BarzoStrike** [comment] 2022-10-20 22:37
I saw that it was reproduce when I reset the server. I don't know how else to reproduce
same problem in guild warehouse

**Comment by moepi2k** [comment] 2022-10-21 00:22
your right. i  checked it. also many report lost items on storage after server restart

**Comment by moepi2k** [comment] 2022-10-21 08:42
@insthync  really important. Always my players items is gone after restart server 🤯

**Comment by insthync** [comment] 2022-10-21 08:43
Only after restart server?

**Comment by moepi2k** [comment] 2022-10-21 10:06
yes it seems so, everytime i restart or shut it down and start, player report missing items from player/guild storage

i just use the killall command to shut down, but i dont think thats the issue

**Comment by insthync** [comment] 2022-10-21 21:54
Try this change: https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/64bcf97ce4b3f3be270a111b42bc72444c582fed

**Comment by moepi2k** [comment] 2022-10-23 10:26
i will push an update with that fix next week, and let you know if it helps. weird is ppls only report that weapons and armors lost from personal storage after restart

**Comment by moepi2k** [comment] 2022-10-23 10:48
ok i tested localy with mysql and the bugfix from above not fixed the problem.
let me share two photos. one directly before restart server and the second directly after restart

Personal Storage before restart:
https://gyazo.com/a71780e173e459b4b71de338928103c9

and after restart:
https://gyazo.com/b203e0c34f9ae752ae4eccf2ec2f32be

somehow the order is diffrent for few items and then some are lost

@insthync

**Comment by moepi2k** [comment] 2022-10-23 11:01
jsut tested on fresh project 177d2 

before restart
https://gyazo.com/da76c1f8224d8b390698df04271287c2
after restart
https://gyazo.com/308884b2a48f10bdf9ef90874e50c4ad

i hope you can find the bug. my playes going crazy :((

**Comment by insthync** [comment] 2022-10-23 11:06
So your problem is items in storage, not in character's inventory?

**Comment by insthync** [comment] 2022-10-23 11:07
So.., I can't reproduce it yet, can you tell me how ?

**Comment by moepi2k** [comment] 2022-10-23 16:05
Character inventory is fine, only in storage.
In the case above, i use player storage from npc. I not tested if same issue is on guild storage and building, but i think guild has same issue because @BarzoStrike had it.

To reproduce:
Just make mmo server put sone items in player storage. Restart server and check player storage again

**Comment by insthync** [comment] 2022-10-23 18:08
I still can't reproduce it, items were not lost (tested with weapon, armor, building, potion and junk)

**Comment by moepi2k** [comment] 2022-10-23 18:19
177d2?
i just made a fresh project, changed nothing and it happen, same as in my main project

**Comment by Callepo** [comment] 2022-10-23 19:01
i tested on 1.78 also with mysql db, and same thing happens.
Step 1 
start server

Step 2
Login player

Step 3
put items in storage, dont close it( even with closing it it still happens, but best result is leave it open. )

Step 4
Kill the server, and the client will dc...

Step 5
Start server again and log char, storage will be empty, and items lost

**Comment by loveTSloveNET** [comment] 2022-10-23 19:02
using v.1.78

Same problem

Here the Discord discussion:
https://discord.com/channels/460801727789137920/460803281455939595/1033816051357589554

![imagen](https://user-images.githubusercontent.com/24850331/197410635-023d2ea6-31d7-47d1-873b-347fcd0102f7.png)

I restarted the client and just in case did a nother login

![imagen](https://user-images.githubusercontent.com/24850331/197410650-5481e40d-32df-45b9-9267-60148c13f95a.png)

And still were appearing

Now i restart the server

and BOOOM! BLANK!

![imagen](https://user-images.githubusercontent.com/24850331/197410672-ddc0db2c-d461-407e-9bb6-95e51d9fc592.png)

**Comment by insthync** [comment] 2022-10-23 19:22
In this video is package version 1.78

https://youtu.be/C6ihIqVdTYI

I found only character's inventory not saving issues (which I have fix)

**Comment by insthync** [comment] 2022-10-23 19:41
Send server log files to me.

**Comment by Callepo** [comment] 2022-10-23 19:47
[Log_Database_Central.log](https://github.com/suriyun-production/mmorpg-kit-docs/files/9847397/Log_Database_Central.log)

here is the errors it throws

**Comment by moepi2k** [comment] 2022-10-23 19:57
i dont know why the items on your side saved in storage, but when you watch your video carefully you will see that all your items which you moved to storage are duped after restart. because they are in storage and still in inventory :)

https://gyazo.com/b306086a316043e16ffe6b73f268f8b6/draw
here
duped
https://gyazo.com/69c2f5b382298c325dac6e3475143358

**Comment by Callepo** [comment] 2022-10-23 20:00
true, even if ur items didnt get lost, they got dupped which is still an issue

**Comment by insthync** [comment] 2022-10-24 05:08
Try this https://github.com/insthync/UnityMultiplayerARPG_MMO/commit/64bcf97ce4b3f3be270a111b42bc72444c582fed , It is item duplicate fixing.

**Comment by moepi2k** [comment] 2022-10-24 06:27
All my videos above are recored already with that. That fix wont fix the duplicate and item lost in storage

**Comment by insthync** [comment] 2022-10-24 06:54
It fix duplicate not fix item lost

**Comment by insthync** [comment] 2022-10-24 06:56
And to fix an item lost as I see in the log files, it is easy  to fix by just change type of storageitem table -> randomSeed to int(11).

That is why you should attach log files so I can find where to fix it easily

**Comment by moepi2k** [comment] 2022-10-24 07:02
Thats weird, in my video above i also have duping bug and i used the changes from you, can you maybe send full fox for dupe and item lost? I will try again

**Comment by insthync** [comment] 2022-10-24 17:07
Try 1.78b, if it is still occuring then tell me later.

**Closed by insthync** 2022-10-24 17:07 UTC

**Comment by temelGameFacto** [comment] 2022-10-25 20:09
I am having same issue about item lost in player storage.When I restart server Items in storage are lost.Pls fix the issue................

**Comment by moepi2k** [comment] 2022-10-25 20:39
its already fixed in latest version.  if you use older version check you mysql db and change tinyint to int for the randomSeed in storageitem tables
