### ISSUE TITLE
"Landed Pause Movement Duration" seems working wrong.

### ISSUE THREAD

**Issue by nakedfighter3d** [suriyun-production/mmorpg-kit-docs#898] opened 2021-03-30 04:47 UTC
Switching to AdvancedCharacterWithLanding _(animator with landing animation)_ brings us to the situation when a character playing landing animation while continuing to move forward. That's a totally expected behavior and I suppose that "Landed Pause Movement Duration" option should solve this issue. 
![LandedSlide](https://user-images.githubusercontent.com/38335953/112934422-bb5dc400-90ef-11eb-96f8-9d865f2a525c.gif)
_(sliding while landed)_

I suppose that this option should stop a character from moving on a certain time value when the jumps end. Seems like it doing something different.  I set the value to 0.25 and it brings two options. In a best-case scenario character just stop moving forward at the very beginning of a jump _(seems like he hit the invisible wall)_, fall down, play landed animation, wait, and then continue running.
![LandedStuckGood](https://user-images.githubusercontent.com/38335953/112934893-b3525400-90f0-11eb-9b4c-c5981114fa0c.gif)

In the worst-case scenario, it also hit the invisible wall at a very beginning of a jump but then he never comes back to running.  
He's stuck in the place and didn't move in x,z space anymore.
![LandedStuckBad](https://user-images.githubusercontent.com/38335953/112935116-1f34bc80-90f1-11eb-9965-f6308166d4f9.gif)

Am I using this option in the wrong way or something actually didn't work as intended?

**Comment by insthync** [comment] 2021-03-30 06:37
It is not work as intended, I will fix it.

**Comment by nakedfighter3d** [comment] 2021-03-30 06:39
Yay! Thanks, you're the best! <3

**Comment by insthync** [comment] 2021-04-12 15:57
Fixed in 1.64

**Closed by insthync** 2021-04-12 15:57 UTC
