### ISSUE TITLE
Item Dublication.

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#1061] opened 2021-07-02 14:14 UTC
https://www.youtube.com/watch?v=-fzYSLyE4Gs 
One of my users sent me this video. In this video, you can see that when he inserted stones into the sockets, the second item turned into the first item.

**Comment by insthync** [comment] 2021-07-08 01:09
Still can't reproduce it yet, I guess that the problem occurring when insert stone quickly

**Comment by DimasjkTV** [comment] 2021-07-11 20:22
> Still can't reproduce it yet, I guess that the problem occurring when insert stone quickly, did you try it?
> 
> You change item list filter by just change filter setting in `UINonEquipItems`, right?
I also failed to reproduce this. Seem to be. this is a very rare occurrence. 
Yes Non equip
![image](https://user-images.githubusercontent.com/47291794/125209031-cd2e3600-e29e-11eb-90a7-2281d0d37393.png)

**Comment by insthync** [comment] 2021-11-01 05:08
I will close this, if it is still occurring, you can reopen it.

**Closed by insthync** 2021-11-01 05:08 UTC
