### ISSUE TITLE
[Bug]Damage Transform -> Apply Damage

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1572] opened 2022-05-19 11:24 UTC
https://gyazo.com/4f29b3adbff9bdec73b619b1bd3e637e

In the Video iuse melee attack with a Hit Distance of 10 and a Hit Fov of 90.

like u can see. damage works normal when i aim in specific direciton.
but when i aim northside and walk westside while attack. the damage goes west side. but u also see that animation and the drawn gizmo is correct northside.

so it seems damage not probebly apply in gizmo location

**Comment by insthync** [comment] 2022-05-20 09:26
I can't reproduce it yet.

**Comment by moepi2k** [comment] 2022-05-20 10:06
maybe this only happen with aimatcursor controller?

**Comment by insthync** [comment] 2022-05-20 10:44
Yes, I testing with it, I guess that it might be because of execution order

**Comment by moepi2k** [comment] 2022-05-20 10:53
projectiles spawns correctly, only happen with melee

**Comment by moepi2k** [comment] 2022-05-20 11:16
i made alot of changes for my aimatcursorcontroller.
i thought its that part of code, so player only face at mouse direction while attacking. else its facing in the direciton u walk

https://gyazo.com/726ffe5e7831b711ac3acfa0763b3e6c

but it seems that also with that part of code it works in default kit.
https://gyazo.com/34f0e2aa45159b30e2568267315aabff

so nvm i need to check whats goin on here. i noticed u made alot of changes in the aimatcursorcontroller. maybe mine is a bit outdated :)

**Comment by moepi2k** [comment] 2022-05-20 11:37
ok i found the bug. happens also in fresh kit.
its also when u set triggerdurationrate to 0. so same as the issue i reported for buffs (whichs is already fixed)

https://gyazo.com/a8161e1c64613b910861ba1296c1f4ff
twohander has 0.5
onehand is set to 0

**Comment by insthync** [comment] 2022-05-20 11:40
Okay

**Comment by insthync** [comment] 2022-06-06 18:55
Fixed in 1.75e

**Closed by insthync** 2022-06-06 18:55 UTC
