### ISSUE TITLE
Mount-Lagging Issue when Players are already logged in

### ISSUE THREAD

**Issue by xnitro1** [suriyun-production/mmorpg-kit-docs#1913] opened 2023-02-16 12:23 UTC
Hey there,

i used the TopDownController with a mount. The problem is, when Player A is already in/on the mount (in my case a car) and Player B Spawns then Player B will see the car lagging.

When Player A then exits the mount and remount its looking fine. When Player B relogs the Player A is still in/on the mount, the lagging begins again until Player A gets of the mount and remount again.

This happens everytime. Is this a bug?

Video of it: https://youtu.be/cJ7W95mwExI

**Comment by moepi2k** [comment] 2023-02-16 14:26
have exactly same issue, but was not able to reproduce. good find

**Comment by xnitro1** [comment] 2023-02-17 13:50
This issue also applies to the normal alpaca, so its not an issue with my new "car" mount.

**Comment by shubhank008** [comment] 2023-02-18 05:30
Potentially similar bug/problem of mount lag
https://github.com/suriyun-production/mmorpg-kit-docs/issues/1397

**Comment by RafaelRBizachi** [comment] 2023-02-18 08:36
> Potentially similar bug/problem of mount lag #1397

did you solve yours? I still have problems with a mount

**Comment by moepi2k** [comment] 2023-02-18 19:34
Im in latest kit without any modifications at mounts and got that issue, so no its not fixed yet

**Comment by xnitro1** [comment] 2023-02-19 11:18
> I have 2 mounts, one that has 1.82 speed of the driver and the other has 2.0 of speed and only the one that has 2.0 that is teleporting does it have something with the speed?

i changed my speed to 1.5 (which makes the vehicle very slow) and it still teleports. so i dont think speed has something todo with the issue. this is definitely something suri should check on, because its a gamebreaking bug regarding mounts

**Comment by insthync** [comment] 2023-02-20 02:31
Fixed in 1.80e

**Closed by insthync** 2023-02-20 02:31 UTC
