### ISSUE TITLE
Missile Entity often do not apply damage (Version 1.85c3)

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2300] opened 2023-11-02 04:35 UTC
After the new Hit register workflows my missile entity rarely hit (does damage) to the enemy. The Entity is getting destroyed on the enemy but do not apply damage.

It looks like this problem occur when the enemy is getting closer to the player.

**Comment by insthync** [comment] 2023-11-02 04:58
When is its end :(

**Comment by Eniotnacram** [comment] 2023-11-02 04:59
> When is its end :(

I know brotha, I am so sorry, seems so hard to find the perfect way to make it work :(

There is a video of the problem if needed:
https://medal.tv/games/requested/clips/1BAElImV3ZiPdT/d1337zzvIaLz?invite=cr-MSxrSzUsNDQ3NDMxODYs

**Comment by insthync** [comment] 2023-11-02 05:25
Hmm.. it should hit because the missile is move straightly

**Comment by Eniotnacram** [comment] 2023-11-02 05:27
> Hmm.. it should hit because the missile is move straightly

Yea.. and the missile directly hit the enemy too. May be related to the speed of the missile? It's at 100. Slower missile seems to do damage more often, speed of 70.

**Comment by insthync** [comment] 2023-11-02 06:10
Yes, maybe

**Comment by Eniotnacram** [comment] 2023-11-02 06:13
Have you any other suggestion for me? Bigger Damageable hitbox? Use projectile entity instead? Increase server FPS?

**Comment by insthync** [comment] 2023-11-02 07:24
Current setting is Missile Damage Entity with 100 speed?

**Comment by Eniotnacram** [comment] 2023-11-02 13:15
Yes this is my Missile entity setting, 100 speed, using raycast, with a sphere collider on it (is trigger on) and a  rigid body. Same setup as the (fire bolt) from the kit, but with more speed. (Using shooter controller)

**Comment by insthync** [comment] 2023-11-02 13:28
Hey, missile damage entity and raycast are not the same kind of damage, not sure that it actually is raycast damage?

This one (1)

![Screenshot_926](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/93cd892d-3ec5-421e-bdb7-4fc575f62f42)

or (2)

![Screenshot_927](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/908fea47-0055-4014-a1dc-b259343a47d1)

**Comment by Eniotnacram** [comment] 2023-11-02 14:25
I use missile, I mean using raycast on the damage entity

**Comment by Eniotnacram** [comment] 2023-11-02 16:10
Can you reproduce the problem?

**Comment by Eniotnacram** [comment] 2023-11-02 17:53
On my end, the missile does damage very fine when the enemy is far, but when the enemy is closer and closer to the player, the worst the damage is getting applied.

**Comment by Eniotnacram** [comment] 2023-11-02 21:26
I also did test in fresh KIT MMO. Using the archer character and the same problem occur. Speed up the weapon type missile speed to 100 and 80% of hits doesnt do damage.

**Comment by Eniotnacram** [comment] 2023-11-03 00:25
Looks like using the Projectile Missile entity is much better! it does damage almost everytime. Thats wierd because it inherit from the MissileDamageEntity but maybe some override make it better

**Comment by moepi2k** [comment] 2023-11-03 08:26
there is no collider on it, the new version of it dont need it anymore. i think u have old prefab in ur project. even stock kit dont have collider attached

**Comment by Eniotnacram** [comment] 2023-11-03 12:25
> there is no collider on it, the new version of it dont need it anymore. i think u have old prefab in ur project. even stock kit dont have collider attached
> 
> unitys physic detectection when using collider is really bad with high speed.

Looks at some, I don't remember which one, but some does have a collider in fresh kit. I think one variation of the arrow does or the fire bolt entity.

But yea glad I know now that we don't need them. But still missile entity is broken real bad using latest kit version. And it works flawlessly using the projectile entity, just need to understand why I guess

**Comment by insthync** [comment] 2023-11-03 12:54
It is having speed hack detection added, you may try delete it in `MissileDamageInfo` -> `IsHitValid` function, and test it.

**Comment by Eniotnacram** [comment] 2023-11-03 13:57
But the Projectile Damage Entity  is using the "MissileDamageInfo" right? And it works fine using it. So I dont think the speed hack detection is faulty

**Comment by insthync** [comment] 2023-11-03 13:58
Did you try to delete it?

**Comment by xnitro1** [comment] 2023-11-03 14:00
What exactly should he delete? Because i have the same problem and after reading this thread, i havent understood what to delete

**Comment by insthync** [comment] 2023-11-03 14:00
Codes in `IsHitValid ` function

**Comment by Eniotnacram** [comment] 2023-11-03 14:20
> Did you try to delete it? Just do what I've told you. If you want to help me to test it, or just tell me that you won't.
> 
> That Projectile Damage Entity has different updating.

Well, with the different updating from the "Projectile Damage Entity" it works very fine. So i think we should simply use the Projectile Damage Entity updating logic in the Missile Damage Entity. It would fix the problem and the Missile Damage Entity would work properly.


But yea, WITHOUT the speed hack in MissileDamageInfo, it works PERFECTLY

        public override bool IsHitValid(HitValidateData hitValidateData, HitRegisterData hitData, DamageableHitBox hitBox)
        {
            float dist = Vector3.Distance(hitData.Origin, hitData.Destination);
            float maxExtents = Mathf.Max(hitBox.Bounds.extents.x, hitBox.Bounds.extents.y, hitBox.Bounds.extents.z);
            // Too far
            if (dist > missileDistance + maxExtents)
                return false;

            // The check for speed hack detection has been removed

            return true;
        }

**Comment by Eniotnacram** [comment] 2023-11-03 14:29
Because it works perfectly using the "Projectile Damage Entity",  and the "speed hack detection" so maybe  the "Missile Damage Entity" should simply be updated to work using the new "speed hack detection". You are the PRO here tho, dont take my words, if you think its better to adjust the "speed hack detection" then let's do it.

**Comment by insthync** [comment] 2023-11-03 14:31
Then try Missile Damage Entity

**Comment by xnitro1** [comment] 2023-11-03 14:45
mh for me its still not working. my missiles are not hitting at all in a certain distance. but maybe i´ll have another problem not related to this

**Comment by Eniotnacram** [comment] 2023-11-03 14:46
> mh for me its still not working. my missiles are not hitting at all in a certain distance. but maybe i´ll have another problem not related to this

what you mean by not hiting at all? going trough the monsters?

**Comment by xnitro1** [comment] 2023-11-03 14:55
yeah its going through i think: https://streamable.com/lg9us2
when the enemy is not that far away, it seems to work. but when he has quite the distance, its not working anymore. but maybe thats another problem on my side and has nothing todo with this anymore (i used your code from above, that atleast seemed to fix it when the monster is not that far away)

**Comment by Eniotnacram** [comment] 2023-11-03 14:56
> yeah its going through i think: https://streamable.com/lg9us2 when the enemy is not that far away, it seems to work. but when he has quite the distance, its not working anymore. but maybe thats another problem on my side and has nothing todo with this anymore (i used your code from above, that atleast seemed to fix it when the monster is not that far away)

yea looks like a problem on your end, are you using the projectile damage entity? you need to set the hit layer

**Comment by insthync** [comment] 2023-11-03 15:01
@Eniotnacram Did you try Missile Damage Entity with speed hack detection removed?

@xnitro1 Seems like it is a different problem, the problem here is it hit then it told the server that it was hit but the server didn't trust the client, your problem is it doesn't hit at all, both the client and server, you must check enemy's hitboxes, may debugging by add debug.log() codes to `MissileDamageEntity` -> `HitDetect` function when it is hitting.

**Comment by Eniotnacram** [comment] 2023-11-03 15:03
> @Eniotnacram Did you try Missile Damage Entity with speed hack detection removed?
> 
> @xnitro1 Seems like it is a different problem, the problem here is it hit then it told the server that it was hit but the server didn't trust the client, your problem is it doesn't hit at all, both the client and server, you must check enemy's hitboxes, may debugging by add debug.log() codes to `MissileDamageEntity` -> `HitDetect` function when it is hitting.

YES! @insthync i did, it works! When the speed hack detection is removed the  Missile Damage Entity works perfectly.

https://github.com/suriyun-production/mmorpg-kit-docs/issues/2300#issuecomment-1792536733

**Comment by insthync** [comment] 2023-11-03 15:10
@Eniotnacram Okay, so both `MissileDamageInfo` and `ProjectileDamageEntity` works perfectly if speed hack detection removed, right?

**Comment by Eniotnacram** [comment] 2023-11-03 15:16
@insthync ProjectileDamageEntity works well even without removing the hack detection from MissileDamageInfo. MissileDamageEntity needs hack detection removed to work properly

**Comment by xnitro1** [comment] 2023-11-03 15:45
> @Eniotnacram Did you try Missile Damage Entity with speed hack detection removed?
> 
> @xnitro1 Seems like it is a different problem, the problem here is it hit then it told the server that it was hit but the server didn't trust the client, your problem is it doesn't hit at all, both the client and server, you must check enemy's hitboxes, may debugging by add debug.log() codes to `MissileDamageEntity` -> `HitDetect` function when it is hitting.

i hope the quality of the video gets better when its processed:
https://streamable.com/00gcj9

i tried the Debug.Log and yes i can see that i hit the enemy, but its not recognized. in the video i hit the enemy serveral times but nothing happens

**Comment by Eniotnacram** [comment] 2023-11-03 15:52
> > @insthync ProjectileDamageEntity works well even without removing the hack detection from MissileDamageInfo. MissileDamageEntity needs hack detection removed to work properly.
> > So that's why I was tempted to try using the logic from the ProjectileDamageEntity in the MissileDamageEntity, because it was working well without removing the hack detection.
> 
> But the problem is occurring because of speed hack detection, isn't it ?

Yes I would say so, without the hack detection, Default Missile Damage Entity works fine

**Comment by insthync** [comment] 2023-11-03 15:57
@Eniotnacram It works by client tell server when to play animation and launch damage entity, then client do hit detection, then when it is hit client tell server that it is hit. All done by client, server just do speed hack detection.

So, that is why it won't be fixed by use updating logic from `ProjectileDamageEntity`

**Comment by insthync** [comment] 2023-11-03 15:59
> > @Eniotnacram Did you try Missile Damage Entity with speed hack detection removed?
> > @xnitro1 Seems like it is a different problem, the problem here is it hit then it told the server that it was hit but the server didn't trust the client, your problem is it doesn't hit at all, both the client and server, you must check enemy's hitboxes, may debugging by add debug.log() codes to `MissileDamageEntity` -> `HitDetect` function when it is hitting.
> 
> i hope the quality of the video gets better when its processed: https://streamable.com/00gcj9
> 
> i tried the Debug.Log and yes i can see that i hit the enemy, but its not recognized. in the video i hit the enemy serveral times but nothing happens. maybe its not another problem? i dont know :D
> 
> (those errors are just from the attack indicator on the client, nothing to do with the KIT)

Why in the first video I saw it pass through the enemy? is it a server-view?

**Comment by xnitro1** [comment] 2023-11-03 16:08
It's just not the fireball from the kit. It's another prefab with another sfx effect. But it's still a missile prefab. In the first video I found the error. The missiles were under the enemy at a certain range. After fixing this I hit the enemy on any distance (that's the debug.log). But the damage is not happening.

**Comment by insthync** [comment] 2023-11-03 16:12
So in the first video it is not relates to problem in this post, right?

**Comment by xnitro1** [comment] 2023-11-03 16:15
Correct. I thought it was, but it wasn't. But the problem now could be (but maybe not. I am not the pro here :D ). All I can say that the client says he hit the target but nothing happens

**Comment by xnitro1** [comment] 2023-11-03 16:22
I don't know what you mean by that. I was just stating that my knowledge is not the best and by far not as good as yours.

**Comment by insthync** [comment] 2023-11-03 16:31
I see, so please don't comment anything that I didn't ask, okay?

**Comment by xnitro1** [comment] 2023-11-03 16:40
yes.

**Comment by Eniotnacram** [comment] 2023-11-03 16:48
> @Eniotnacram It works by client tell server when to play animation and launch damage entity, then client do hit detection, then when it is hit client tell server that it is hit. All done by client, server just do speed hack detection.
> 
> So, that is why it won't be fixed by use updating logic from `ProjectileDamageEntity` if problem is speed hack detection

Ok I do understand. So for some reason, the server accepting the data from the ProjectileDamageEntity but not from the MissileDamageEntity. Maybe the ProjectileDamageEntity give more precise data to the server so the speed hack accept it?

**Comment by insthync** [comment] 2023-11-03 20:10
Are you really want to know? Should I write a document to explain or fix it first?

**Comment by Eniotnacram** [comment] 2023-11-03 20:20
> Do you really want to know? If yes, then I think I have to write a document, Should I write a document to explain or fix it first? Fix it might be easier by just change that 3 lines of calculation codes.

I dont need to know, you can fix it, dont worry :)

**Comment by Callepo** [comment] 2023-11-04 01:22
hmm
Tested Missiles, with latest Pull from Repo, in mmo, using Bow and MissileDamageEntity. I didnt miss a single time when attacking
Used literally all the 100 bullets in my inventory
https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/3b390be5-2b0f-4a94-bb22-e2f9d64ae945

And this is raycast With Guns

https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/306c5bd8-e502-4bf0-b3bd-6764bca61f92


Ive never seen the kit more accurate than this lol..
Raycasting use to be u hit once every 50 shots..

**This is old Raycasting.. Compare the 2 together urself lol**
https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/3e2fb01d-3dc8-4a8b-8ebc-35396a515bc2


**This is old Missile before the MissileDamageInfo**
https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/151771a2-c1af-49b6-b5d0-098f0ba637f4

**Comment by Callepo** [comment] 2023-11-04 01:33
P.S, they are doing missile at over 100 speeds, which is too fast and making the arrow pass the hitbox before it can register in the Update.. To high of a speed for a collidor is a unity engine failing issue..

**Comment by Callepo** [comment] 2023-11-04 01:45
The issue is they have it for high speeds like 100+
Missile Works flawlessly at normal speeds, 
But at 100
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/d20e58aa-c128-4641-b2ef-a0493be69c34)

This literally returns false everytime

**Comment by Callepo** [comment] 2023-11-04 02:01
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/92fcc7e5-4813-4209-bcb2-6e0ea8c592c0)
 Lowering the 0.8 to 0.2 it works fine even at Speed = 100.. but idk how it would effect speed hack detection..
 the time is an issue if u have a too high speed, to avoid this, missile should limit speeds that can be calculated by the calculations.. 
 
 Or just lower it and be like fuck it.. idk lol
 
 This was original

https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/6086eff5-6907-40ad-9ff8-1bbcadbf601c

**Comment by Callepo** [comment] 2023-11-04 02:03
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/92fcc7e5-4813-4209-bcb2-6e0ea8c592c0)
 Lowering the 0.8 to 0.2 it works fine even at Speed = 100.. but idk how it would effect speed hack detection..
 the time is an issue if u have a too high speed, to avoid this, missile should limit speeds that can be calculated by the calculations.. 
 
 Or just lower it and be like fuck it.. idk lol
 
 This was original

https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/6086eff5-6907-40ad-9ff8-1bbcadbf601c

**Comment by Callepo** [comment] 2023-11-04 02:10
PLS DO NOT CHANGE HOW HIT VALIDATION IS WORKING ETC, This is literally best ive seen it work in 3 years..
The only issue is the 0.8 time frame is not low enough for high velocity, it should be lower or have a better formula
that is all!

**Comment by Eniotnacram** [comment] 2023-11-04 02:11
@Callepo glad you came and help us figure it out. So yea, I would say that the kit has never been THAT good for the missile, raycast and stuff. The only problem was it wasnt doing damage, but we figured out why. Now we have some options, either lowering the timer of the speed hack, or clamping the speed for the missile entity to min or max (not over 60).

**Comment by insthync** [comment] 2023-11-05 05:29
> PLS DO NOT CHANGE HOW HIT VALIDATION IS WORKING ETC, This is literally best ive seen it work in 3 years.. The only issue is the 0.8 time frame is not low enough for high velocity, it should be lower or have a better formula that is all!

Yes that is exactly what I am going to do, but the situation is one said it works perfectly if speed detection disabled but another one siad it is not, so I want to make sure that what is the cause of problem.

**Comment by moepi2k** [comment] 2023-11-05 10:43
i tested also both in 185c3 and as calle said, its best we have since ever. only the IsHitValid formula need to be better for high velocity projectiels. 0.8 works with slow one. but not with higher velocity. i tested 0.2 with velocity 200 and it works but i dont know that an effect it has when changing that number.

**Comment by moepi2k** [comment] 2023-11-05 10:57
so this works pretty well, tested with speed of 200 and all hits registered

`public override bool IsHitValid(HitValidateData hitValidateData, HitRegisterData hitData, DamageableHitBox hitBox)
        {
            float dist = Vector3.Distance(hitData.Origin, hitData.Destination);
            float maxExtents = Mathf.Max(hitBox.Bounds.extents.x, hitBox.Bounds.extents.y, hitBox.Bounds.extents.z);

            // Too far
            if (dist > missileDistance + maxExtents)
                return false;

            float duration = (hitData.HitTimestamp - hitData.LaunchTimestamp) * 0.001f;

            // Duration must be greater than zero to avoid division by zero
            if (duration <= 0)
                return false;

            // Calculate the relative speed (as a ratio of expected missile speed)
            float relativeSpeed = (dist / duration) / missileSpeed;

            // Define the acceptable lower and upper bounds for relative speed
            float lowerBound = 0.8f; // or some other threshold that makes sense for your scenario
            float upperBound = 1.5f; // assuming 150% of missileSpeed is the upper limit for high velocity

            // Check that the relative speed is within the acceptable bounds
            if (relativeSpeed < lowerBound || relativeSpeed > upperBound)
                return false;

            return true;
        }`

i think noone will ever use higher speed of 200 so u maybe can clamp the inspector value to max 200 for missiledamageentity

**Comment by Eniotnacram** [comment] 2023-11-05 12:29
Thanks y'all for your participation in this. @insthync so yes, @Callepo @moepi2k are right, the only thing to modify is the isHitValid to make it work with a higher velocity missile.

**Comment by Callepo** [comment] 2023-11-05 14:12
> float duration = (hitData.HitTimestamp - hitData.LaunchTimestamp) * 0.001f;
> 
>         // Duration must be greater than zero to avoid division by zero
>         if (duration <= 0)
>             return false;
> 
>         // Calculate the relative speed (as a ratio of expected missile speed)
>         float relativeSpeed = (dist / duration) / missileSpeed;
> 
>         // Define the acceptable lower and upper bounds for relative speed
>         float lowerBound = 0.8f; // or some other threshold that makes sense for your scenario
>         float upperBound = 1.5f; // assuming 150% of missileSpeed is the upper limit for high velocity
> 
>         // Check that the relative speed is within the acceptable bounds
>         if (relativeSpeed < lowerBound || relativeSpeed > upperBound)
>             return false;

if his doesnt work with it disabled, than his shit is messed up, and not related  to the missiles. he should figure out what he broke

**Comment by Callepo** [comment] 2023-11-05 14:15
> so this works pretty well, tested with speed of 200 and all hits registered
> 
> `public override bool IsHitValid(HitValidateData hitValidateData, HitRegisterData hitData, DamageableHitBox hitBox) { float dist = Vector3.Distance(hitData.Origin, hitData.Destination); float maxExtents = Mathf.Max(hitBox.Bounds.extents.x, hitBox.Bounds.extents.y, hitBox.Bounds.extents.z);
> 
> ```
>         // Too far
>         if (dist > missileDistance + maxExtents)
>             return false;
> 
>         float duration = (hitData.HitTimestamp - hitData.LaunchTimestamp) * 0.001f;
> 
>         // Duration must be greater than zero to avoid division by zero
>         if (duration <= 0)
>             return false;
> 
>         // Calculate the relative speed (as a ratio of expected missile speed)
>         float relativeSpeed = (dist / duration) / missileSpeed;
> 
>         // Define the acceptable lower and upper bounds for relative speed
>         float lowerBound = 0.8f; // or some other threshold that makes sense for your scenario
>         float upperBound = 1.5f; // assuming 150% of missileSpeed is the upper limit for high velocity
> 
>         // Check that the relative speed is within the acceptable bounds
>         if (relativeSpeed < lowerBound || relativeSpeed > upperBound)
>             return false;
> 
>         return true;
>     }`
> ```
> 
> i think noone will ever use higher speed of 200 so u maybe can clamp the inspector value to max 200 for missiledamageentity

tried this, it still misses alot, and only used 120 speed, the 0.8 lower bound needs to be lower for high speeds

**Comment by Callepo** [comment] 2023-11-05 15:09
@insthync 
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/f55bfaa3-7166-441c-a342-f22e3481efc9)

i did this, it changes the static variable, based on missile speed, which goes up and down 
Tried 150 speed and works fine..
And it still checks for speed hack, becuase if the speed is not same as server it will not match and return false.

**Comment by Callepo** [comment] 2023-11-05 15:16
`public override bool IsHitValid(HitValidateData hitValidateData, HitRegisterData hitData, DamageableHitBox hitBox)
        {
            float dist = Vector3.Distance(hitData.Origin, hitData.Destination);
            float maxExtents = Mathf.Max(hitBox.Bounds.extents.x, hitBox.Bounds.extents.y, hitBox.Bounds.extents.z);
            // Too far
            if (dist >= missileDistance + maxExtents)
                return false;

            float duration = (float)(hitData.HitTimestamp - hitData.LaunchTimestamp) * 0.001f;
            // Take too short time to hit
            if (Mathf.Abs((dist / duration) / missileSpeed) < 0.8f - (missileSpeed * 0.002f))
                return false;
            return true;
        }`

**Comment by Eniotnacram** [comment] 2023-11-05 17:28
> > float duration = (hitData.HitTimestamp - hitData.LaunchTimestamp) * 0.001f;
> > ```
> >     // Duration must be greater than zero to avoid division by zero
> >     if (duration <= 0)
> >         return false;
> > 
> >     // Calculate the relative speed (as a ratio of expected missile speed)
> >     float relativeSpeed = (dist / duration) / missileSpeed;
> > 
> >     // Define the acceptable lower and upper bounds for relative speed
> >     float lowerBound = 0.8f; // or some other threshold that makes sense for your scenario
> >     float upperBound = 1.5f; // assuming 150% of missileSpeed is the upper limit for high velocity
> > 
> >     // Check that the relative speed is within the acceptable bounds
> >     if (relativeSpeed < lowerBound || relativeSpeed > upperBound)
> >         return false;
> > ```
> 
> if his doesnt work with it disabled, than his shit is messed up, and not related to the missiles. he should figure out what he broke

I agree, missiles works extremely well except the IsHitValid. Nothing needs to be modified except this.

**Comment by darkkriteus** [comment] 2023-11-13 20:54
Good afternoon, I also did the tests on 185c3, I was having this problem, in addition to disabling hack detection, there is another problem that must be the case with the other guy.

the other problem is in the detection configuration, if you use MissisleDamageEntity and use HitDetectionMode as sphere or other than raycast, then it doesn't hit targets very far away, only up close, the solution I had was to set HitDetectionMode as raycast, and use a collider component such as a sphereCollider or another, how Firebolt is configured. This way it will always collide correctly, I hope I helped :)

**Comment by insthync** [comment] 2023-11-14 03:45
@darkkriteus Do you saw it hit and disappeared at client?

**Comment by Eniotnacram** [comment] 2023-11-14 13:12
> @darkkriteus Do you saw it hit and disappeared at client?

The hit and disappearance is due to the speed hack. Will be fixed next update

**Comment by darkkriteus** [comment] 2023-11-14 18:28
> @darkkriteus Do you saw it hit and disappeared at client?
Yes, it hits, but it doesn't cause damage, any HitDetectionMode option other than raycast causes this problem




> > @darkkriteus Do you saw it hit and disappeared at client?
> 
> The hit and disappearance is due to the speed hack. Will be fixed next update

the HitDetectionMode problem is different from the SpeedHack problem

**Comment by darkkriteus** [comment] 2023-11-14 18:30
> @darkkriteus Do you saw it hit and disappeared at client?
Yes, it hits but does not cause damage, any HitDetectionMode option other than raycast causes this problem



> > @darkkriteus Do you saw it hit and disappeared at client?
> 
> The hit and disappearance is due to the speed hack. Will be fixed next update

the HitDetectionMode problem is different from the SpeedHack problem

**Comment by darkkriteus** [comment] 2023-11-14 18:42
@Edit

So I did more tests, I noticed that if the size of the Collider type is greater than 5, it starts to fail.
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/49356246/bc17b9f6-2096-4f58-9e7a-430c3ce8aade)
with this size it works More than that it starts to cause problems

**Comment by moepi2k** [comment] 2023-11-14 19:25
im sure it a wrong setting on ur side. radius that size will automaticly collide on instaniate. normal player have a size of 2. so when u go bigger u collide with ground

**Comment by Eniotnacram** [comment] 2023-11-14 21:40
My game works entirely using missile, been playing with them for a year, and they finally work fine now. The only problem now is the speed hack stuff, I'm positive to say that any other problem related to the missiles are caused by a bad configuration.

**Comment by darkkriteus** [comment] 2023-11-14 22:58
> tenho certeza de que é uma configuração errada do seu lado. raio desse tamanho colidirá automaticamente na instanciação. jogador normal tem tamanho 2. então, quando você aumenta, você colide com o solo

No, because I set it so that Projectile doesn't collide with the ground

**Comment by moepi2k** [comment] 2023-11-15 09:02
you dont neeed to have a collider attached to it, and spherecastradius has nothing todo with a collider component. also the size u set is wrong. 1) it make no sense to make that big size, becasue the size is bigger than your player so it already collider with nearby stuff (ground). thats the reason why it only work for nearby target

**Comment by Callepo** [comment] 2023-11-15 13:05
> Good afternoon, I also did the tests on 185c3, I was having this problem, in addition to disabling hack detection, there is another problem that must be the case with the [xnitro1](https://github.com/xnitro1)
> 
> the other problem is in the detection configuration, if you use MissisleDamageEntity and use HitDetectionMode as sphere or other than raycast, then it doesn't hit targets very far away, only up close, the solution I had was to set HitDetectionMode as raycast, and use a collider component such as a sphereCollider or another, how Firebolt is configured. This way it will always collide correctly, I hope I helped :)

This is not true

**Comment by Callepo** [comment] 2023-11-15 13:05
> @edit
> 
> So I did more tests, I noticed that if the size of the Collider type is greater than 5, it starts to fail. ![image](https://user-images.githubusercontent.com/49356246/282888166-bc17b9f6-2096-4f58-9e7a-430c3ce8aade.png) with this size it works More than that it starts to cause problems

also not true

**Comment by Callepo** [comment] 2023-11-15 13:06
This is my Missile Damage Entity prefab, from default kit.. i only changed the Distance the player can shoot.. from 5 to 20.. so its far away..
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/c6ecde33-0f5b-491e-8185-bb8222ffe51d)

i didnt change anything on the prefab, its using Same Sphere cast u said didnt work from far distance if radius not massive..

**Comment by Callepo** [comment] 2023-11-15 13:09
@darkkriteus u have something wrong on ur side, idk what it is, but what u said above every thing i tested proved otherwise.
there is 3 people saying the same thing that what ur saying is not correct and its probably something ur doing wrong on something else

**Comment by Callepo** [comment] 2023-11-15 13:17
@darkkriteus im doing next test, by changing the Hitvalidation code, with what i said above that makes it better at high speeds
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/210dbd88-bff7-457b-ab42-d814c80084dc)

With same Radiuis on my sphere cast, which is 0.3.. default..

changed distance from 20 to 30 now
speed from 60 to 150
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/f5942542-3b35-449d-bf9e-e60fbaf52a03)

IDK what else u wanna see, Not 1 single arrow missed..


@insthync 
https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/36721440-856e-4248-b58f-d9e67a3ba9a2

**Comment by darkkriteus** [comment] 2023-11-16 19:05
do the test with a large sphere radius, I said that the problem is with it being too big, not when it is small

- Also disable to collide with the ground, so that the very large radius does not collide with the ground

**Comment by Callepo** [comment] 2023-11-16 19:08
> do the test with a large sphere radius, I said that the problem is with it being too big, not when it is small
> 
> * Also disable to collide with the ground, so that the very large radius does not collide with the ground

making it too big is as pointless as it sounds.. "TOO BIG"...
if ur radius is bigger than ur character, obvs its gonna hit the ground or ur own character before it even starts moving.. 

Whats the point of making it too big? 
Whats the reason u wanna make it "too big" for? do u have a purpose for this ?

Its like saying, throw a wrench in ur engine, and tell me if it drives good..

**Comment by darkkriteus** [comment] 2023-11-16 19:08
> you dont neeed to have a collider attached to it, and spherecastradius has nothing todo with a collider component. also the size u set is wrong. 1) it make no sense to make that big size, becasue the size is bigger than your player so it already collider with nearby stuff (ground). thats the reason why it only work for nearby target

and who said I added a collider component? and there is no way for the sphera to collide with the ground, if it was disabled to collide with the ground, only with Monsters

**Comment by darkkriteus** [comment] 2023-11-16 19:11
> > do the test with a large sphere radius, I said that the problem is with it being too big, not when it is small
> > 
> > * Also disable to collide with the ground, so that the very large radius does not collide with the ground
> 
> making it too big is as pointless as it sounds.. "TOO BIG"... if ur radius is bigger than ur character, obvs its gonna hit the ground or ur own character before it even starts moving..
> 
> Whats the point of making it too big? Whats the reason u wanna make it "too big" for? do u have a purpose for this ?
> 
> Its like saying, throw a wrench in ur engine, and tell me if it drives good..

I'm just trying to report the problem, and as I said, the projectile hits the enemy, and doesn't cause damage, so if it travels to the enemy, how does it hit the ground? Not to mention that collision with the ground has been disabled, only against monsters.

**Comment by Callepo** [comment] 2023-11-16 19:17
1) u do know clients can display 1 thing and server another right?? meaning, not just becuase it" hit " the monster on ur client it did on server, and having a massive radius is straight up stupid, and pointless.. in every single test i did, there was not a single issue
2) We been saying from the start, that it could be a user error, and saying by what ur saying just confirms it, i see literally not a single reason to have a collidor on a missile bigger than the actual player and having to disable all collision except monster to just have a missile be able to work, just listen to what ur saying.. 
3) if suri had to go make the full kit idiot proof, we would never progress

u have still to mention any usecase where this is needed in an actual environment.
Instead of delaying the actual issue, and finding a solution, to the actual issue, which is the speedhack validation calculation not being optimal for high speeds of missiles, we are here discussing
" An oversized radius on a missile that is bigger than the actual player, which u have to specifically disable all collision, including ground, to just have it be able to move, and try to hit a monster.. "

**Comment by Callepo** [comment] 2023-11-16 19:19
![image](https://github.com/suriyun-production/mmorpg-kit-docs/assets/7702658/a55f82d1-b5cc-4c16-91f0-320d7aab3c15)
This make any sense to u ?

**Comment by darkkriteus** [comment] 2023-11-16 19:24
Okay, it's my mistake then, don't talk about it anymore

**Comment by xnitro1** [comment] 2023-11-16 21:23
Just calm down... nobody is commanding anyone. He has a problem and dont feel he got heard. Now he is not expecting any help anymore. And calling his problem "dumb shit" is also Not very friendly. So let's just calm down and drop this matter. Suri knows about the speed stuff and Dark is Not expecting anything anymore. This Thread should be closed before someone says anything he might regret later. Let's be adults.

**Comment by Callepo** [comment] 2023-11-16 21:37
> Just calm down... nobody is commanding anyone. He has a problem and dont feel he got heard. Now he is not expecting any help anymore. And calling his problem "dumb shit" is also Not very friendly. So let's just calm down and drop this matter. Suri knows about the speed stuff and Dark is Not expecting anything anymore. This Thread should be closed before someone says anything he might regret later. Let's be adults.

it wont go that far, dw, also im calm as can be, im just very direct, even asked multiple times, whats his usecase was or why he needed this, or in what scenario this would be viable, to try and find a solution for him, which i never got a response for, and how he was replying to every comment on his matter i didnt like :) nor how he spoke.
sometimes even adults needs a reality check. 

Also suri closes threads once the matter have been attended to, which he will do on his own time

**Closed** 2023-11-18 17:19 UTC
