### ISSUE TITLE
(PAID REQUEST) morph (transformation) system

### ISSUE THREAD

**Issue by gochaboy1** [suriyun-production/mmorpg-kit-docs#2449] opened 2024-04-11 12:35 UTC
We need to make a transformation system, preferably with the help of a buff.

The character should only change his appearance to another entity (prefab model) with a component (Playable character model) which will have its own animations of movement, attack and everything that a regular character has. The video clearly demonstrates what I would like to receive.

And so the end result should look something like this
The character receives a buff (no matter in what way) for example for 60 minutes, this buff identifies the transformation for example by number (100 = model1, 101 = model2, 103 = model3 and so on) after the character has received the entity identifier buff, we use another ( universal buff) which will change the main character model to an entity model (depending on which identifier buff is hanging on the character)

https://youtu.be/7CA07v2a7aU

**Comment by gochaboy1** [comment] 2024-04-11 17:47
@insthync Can I ask you this as a developer?

**Comment by darkkriteus** [comment] 2024-04-12 01:28
I support that, it would be amazing

**Comment by insthync** [comment] 2024-04-12 06:22
I don't want to accept any paid request, because I don't have time to do it, the kit currently have many bugs to fix, many of you telling me to focus on bugs fixing and performance improvement, but still request for new features :')

For paid requests, many features adding is not easy nowaday, because anything can affect other customer's project, especially anything relates to character movement and abilities.

Then when new features added then new bugs can occurs, most of customer cannot makes bugs reporting efficiency, I have to find how to reproduce a lots of bugs by myself, it is take a lots of time, some of them also not update the kit, but report bugs of an older versions, someone wants to hire me to help them to update but cannot pay for it.

And... I actually never earn money that worth for my time by any paid requests, might be because the kit is too cheap so other paid requests have to be cheap too :)

@gochaboy1 you can ask anything, but can you please just don't tag me like you need an answers immediately,

I don't know that you want to know how I am going to implement it or not, but I will tell you.

This one is hard, because of Unity mesh system, the easiest way to implement it might be disable character's mesh/bones then instantiates a new model into entity transform as its child, but I believe that you guys will asks for root motion supports, and it must be differently for each characters, so this will not works, 

The way which I think it will works well is to despawn the player character entity when morphing then spawn a morphed entity.

Another way is implement this feature by mounting system (vehicle entity), which will hide the character entity while mounting/riding on vehicle entity, this way is easier.

From what I've told you, then I want to know, can you implement it by yourself?, if you can't, then it seems like what I am telling you is just useless because what I have told is not helpful, so it is better just waiting for me to implement it.

**Comment by insthync** [comment] 2024-04-12 08:21
What is that grid system?

But overall, as I read, you better just waiting for me, that is it.

**Comment by gochaboy1** [comment] 2024-04-12 08:55
> What is that grid system?
> 
> But overall, as I read, you better just waiting for me, that is it.

Yes of course, I'm looking forward to it

**Comment by insthync** [comment] 2024-04-12 09:15
How much can you offer to me?

**Comment by gochaboy1** [comment] 2024-04-12 09:19
> How much can you offer to me?

I don’t know how much it costs and I don’t want to belittle other people’s work, so tell me the price, if it’s acceptable for me, then there’s no problem!

**Comment by gochaboy1** [comment] 2024-04-12 09:51
> It is around 15 USD / Hrs. * 6 Hrs.?
> 
> = 90 USD, more expensive than the kit's price.
> 
> That is why I felt hesitate to accept paid requests, The codes will be shared to other customer, so you might not like it because you'd think it should be yours only
> 
> In the past, I had try to tell customers to share the price with other, but it is not success, it has only a very few people pay for it. So I feels it is not fair for the one who paid most.

No problem, do you have binance?

**Comment by gochaboy1** [comment] 2024-04-13 09:38
So where should I send it?

**Comment by masterVoo** [comment] 2024-04-14 19:51
This is incredibly cool, will it be done?

**Comment by gochaboy1** [comment] 2024-04-15 09:28
> This is incredibly cool, will it be done?

I don’t know, I’m ready to pay for the work and I’m also waiting for the developer to respond.

**Comment by BJPickles** [comment] 2024-04-16 13:50
As Suri mentioned you can just do this with the existing mount system. Combat still works.

**Comment by gochaboy1** [comment] 2024-04-16 14:11
> This is made with the kit: https://i.imgur.com/ZDDIDfn.mp4

It looks right! Is it possible to give different monsters different stats in this way? For example, with the help of a buff, we could transfer any characteristics to each monster (morph), and also set the duration of this buff.

I just don’t know at all how what you say works, because I have questions in front of my eyes!

**Comment by BJPickles** [comment] 2024-04-16 14:13
> > This is made with the kit: https://i.imgur.com/ZDDIDfn.mp4
> 
> It looks right! Is it possible to give different monsters different stats in this way? For example, with the help of a buff, we could transfer any characteristics to each monster (morph), and also set the duration of this buff.
> 
> I just don’t know at all how what you say works, because I have questions in front of my eyes!

You'll need to go to the docs and read them, and try things out in your game. :)

**Comment by gochaboy1** [comment] 2024-04-16 14:28
> > > This is made with the kit: https://i.imgur.com/ZDDIDfn.mp4
> > 
> > 
> > It looks right! Is it possible to give different monsters different stats in this way? For example, with the help of a buff, we could transfer any characteristics to each monster (morph), and also set the duration of this buff.
> > I just don’t know at all how what you say works, because I have questions in front of my eyes!
> 
> You'll need to go to the docs and read them, and try things out in your game. :)

Still, this is a clumsy method of implementation. This looks like what is required, but there are a number of restrictions, and the transformation method itself must be different from calling a mount!
 I would prefer a separate morphing system, and would gladly pay for it as soon as the developer becomes available

**Comment by masterVoo** [comment] 2024-04-17 12:13
@insthync  I am also very interested in whether this will be done?

**Comment by BJPickles** [comment] 2024-04-17 12:15
> > > > This is made with the kit: https://i.imgur.com/ZDDIDfn.mp4
> > > 
> > > 
> > > It looks right! Is it possible to give different monsters different stats in this way? For example, with the help of a buff, we could transfer any characteristics to each monster (morph), and also set the duration of this buff.
> > > I just don’t know at all how what you say works, because I have questions in front of my eyes!
> > 
> > 
> > You'll need to go to the docs and read them, and try things out in your game. :)
> 
> Still, this is a clumsy method of implementation. This looks like what is required, but there are a number of restrictions, and the transformation method itself must be different from calling a mount! I would have preferred a separate morphing system and would happily pay for it when Suri has the time.

Pay him $90 here: https://ko-fi.com/insthync

**Comment by BJPickles** [comment] 2024-04-17 12:16
> @insthync I am also very interested in whether this will be done?

@masterVoo you don't need to ping him. Literally scroll up and he's asked not to do that. Don't be rude.

**Comment by BJPickles** [comment] 2024-04-17 12:20
Also all of you reading stop being so impatient and acting so self entitled. Have a little respect for Suri and just wait for him to respond.

Do you honestly think he will do if you're acting like impatient children DEAMANDING something?

No.

So either shut up and wait, or do it yourselves.

**Comment by gochaboy1** [comment] 2024-04-17 16:49
> > > > > This is made with the kit: https://i.imgur.com/ZDDIDfn.mp4
> > > > 
> > > > 
> > > > It looks right! Is it possible to give different monsters different stats in this way? For example, with the help of a buff, we could transfer any characteristics to each monster (morph), and also set the duration of this buff.
> > > > I just don’t know at all how what you say works, because I have questions in front of my eyes!
> > > 
> > > 
> > > You'll need to go to the docs and read them, and try things out in your game. :)
> > 
> > 
> > Still, this is a clumsy method of implementation. This looks like what is required, but there are a number of restrictions, and the transformation method itself must be different from calling a mount! I would have preferred a separate morphing system and would happily pay for it when Suri has the time.
> 
> Pay him $90 here: https://ko-fi.com/insthync

To do this you need to wait for the suri itself

**Comment by insthync** [comment] 2024-04-17 17:22
Okay, please wait guys. I also have plans to change a bit of mount structure, it should have level, duration so the data structure have to be changed

**Comment by gochaboy1** [comment] 2024-04-17 17:33
> Okay, please wait guys. I also have plans to change a bit of mount structure, it should have level, duration so the data structure have to be changed

Thanks Suri, keep in mind that this applies to the method you suggested using mounting.

The "Trigger duration rate" option that is installed on component "Playable character model" attached to the "mount" is not taken into account during combat.
I didn’t find any problems with animations and other things; at first glance, everything works correctly! However, the "Trigger duration rate" option  is taken from the main character and not from the mount

**Comment by insthync** [comment] 2024-04-17 17:36
Yes, it is works as intended, will have to change something.

**Comment by masterVoo** [comment] 2024-04-25 16:11
> Yes, it is works as intended, will have to change something.

I wouldn't like to inconvenience you, I just would like to know if this will be done soon or not? maybe with some kind of update? just the road map is broken mmo-kit is broken, no information!

**Comment by BJPickles** [comment] 2024-04-25 16:16
@masterVoo you need to chill. Suri literally asked you to wait lol

If he said he's going to do it, Suri will do it

**Comment by masterVoo** [comment] 2024-04-25 16:27
> @masterVoo you need to chill. Suri literally asked you to wait lol
> 
> If he said he's going to do it, Suri will do it

Did I ask your opinion? Why are you interfering in someone else's conversation? With your answers you show yourself from the bad side.

**Comment by BJPickles** [comment] 2024-04-25 16:29
> > @masterVoo you need to chill. Suri literally asked you to wait lol
> > If he said he's going to do it, Suri will do it
> 
> Did I ask your opinion? Why are you interfering in someone else's conversation? With your answers you show yourself from the bad side.

Enjoy being mad bro 😂

**Comment by masterVoo** [comment] 2024-04-25 16:31
> > > @masterVoo you need to chill. Suri literally asked you to wait lol
> > > If he said he's going to do it, Suri will do it
> > 
> > 
> > Did I ask your opinion? Why are you interfering in someone else's conversation? With your answers you show yourself from the bad side.
> 
> Enjoy being mad bro 😂

And you keep doing the sycophancy, bro!

**Comment by insthync** [comment] 2024-04-26 03:30
Feels a bit weird when who gonna pay me is stop asking but another who aren't giving any helpful is keeping asking for ETA.

My answer is I don't know too, I didn't start it yet, that is it.

Now you got my answer, then is it benefit anything, if not then that is the reason why I don't answer.

I saw you said about things are broken, if it is then you should address me to know what are them, it will be helpful.

**Comment by insthync** [comment] 2024-04-26 03:32
This kit is not my main source of income, I almost made it open-source, but I won't because I know it will have people like you who keep asking for new features without any helping, hope you guys understanding me :)

**Comment by gochaboy1** [comment] 2024-04-27 05:40
> Feels a bit weird when who gonna pay me is stop asking but another who aren't giving any helpful is keeping asking for ETA.
> 
> My answer is I don't know too, I didn't start it yet, that is it.
> 
> Now you got my answer, then is it benefit anything, if not then that is the reason why I don't answer.
> 
> I saw you said about things are broken, if it is then you should address me to know what are them, it will be helpful.

To be honest, I'm not much of a substitute.

1) When I said that I was satisfied with everything and I was ready to pay, you stopped answering.

2) You asked not to disturb you again and not to mention you

3) You said that you would do this after some time

For these reasons, I am not writing anything here and am just waiting in the hope that it will be done in a reasonable future!

I don’t understand at all what you are going to do, and asking about this in advance is a little awkward for me, considering how they react to questions here or when they ask you about something in person!

**Comment by insthync** [comment] 2024-04-27 12:18
@gochaboy1 now, are you understand?

**Comment by gochaboy1** [comment] 2024-04-27 16:22
> @gochaboy1 now, are you understand?

no not really =)
 
I'm just waiting hoping that it will be done, this is very important to me.

If necessary, I am ready to pay, if not, then I just wait.

**Comment by x0r10** [comment] 2024-05-02 22:51
> This kit is not my main source of income, I almost made it open-source, but I won't because I know it will have people like you who keep asking for new features without any helping, hope you guys understanding me :)

I am also interested in this system, if you are ready to do it, I am ready to pay $ 100

**Comment by insthync** [comment] 2024-05-03 04:24
Please wait, I want to clear other older paid requests first (ladder climbing), then I will do this one later

**Comment by Gryml0k** [comment] 2024-05-29 01:32
I have been attempting to implement my own similar system, by working off the vehicle system. I too would donate to a morphing system if it would help.

I do have a question about the vehicle system though. If I wanted to add weapons to a vehicle, would I use the equip container setter system on the vehicle model? Because I had attempted this and the animations were fine, but the weapon models wouldn't instantiate. And I was hoping to have a separate UI for the vehicle, so I could equip weapons, chests etc on the vehicle. I attempted to duplicate the ItemsDialog, and designated the slots to different types that would not be used by the character to not have multiple instances of the icons etc. But this didn't seem to help. So my question is, will I need to go as far as creating a completely new item struct similar to CharacterItem, but for Vehicles "VehicleItem" ? I didn't get this far, but figured I would ask you if it even seems plausible or if there is an easier way to implement mount weapons.

Thank you for all the hard work you do. Cheers,

**Comment by insthync** [comment] 2024-05-29 05:27
- Have to change mount data structure, it must be stored on another table with a field to telling when the mount will be despawned, we also can use this structure as persistence pet system. 
- Have to change mount action animation system to make it works properly while morphed.
- For mount's items, must have a new table for mount item storing.

**Comment by Gryml0k** [comment] 2024-05-29 07:08
Ok, I will give it a shot. If I come out successful I will let you know. And you read my mind about the persistent pet system, because I was going to implement it for pets if it worked for mounts. ;)

**Comment by insthync** [comment] 2024-08-13 18:17
https://ko-fi.com/insthync/goal?g=0

If it reached a goal within a week then I will start the development, if not I will skip to other ones

**Comment by DageTheReaper** [comment] 2024-11-19 10:14
Is this released into 1.90b?
![chrome_54M30o8wme](https://github.com/user-attachments/assets/b1b24949-11a3-44c2-934b-93b90dd3d9f5)

**Comment by insthync** [comment] 2024-11-19 10:15
@DageTheReaper Intend to made it for the guy who paid for this only

**Comment by DageTheReaper** [comment] 2024-11-19 10:17
If I send some money to your KoFi can I also get it?

**Comment by insthync** [comment] 2024-11-19 10:18
Send it to @gochaboy1

**Comment by DageTheReaper** [comment] 2024-11-19 10:23
Sure. 
Is there a git for it?

**Comment by gochaboy1** [comment] 2024-11-19 14:34
This system will never be publicly available! if you want to get the morphing system for personal use, you have to pay 120$ 
address for donation 
https://ko-fi.com/insthync
@insthync  

By purchasing this system, you not only purchase a plugin, but also support the developer. 
No need to private message me, I'm not selling anything.

**Closed** 2024-12-01 07:06 UTC
