### ISSUE TITLE
% attributes

### ISSUE THREAD

**Issue by DimasjkTV** [suriyun-production/mmorpg-kit-docs#106] opened 2019-10-16 20:01 UTC
We have item with 100 int and 50% int. Character has 100 int from points. We equip item and character have 250 int. But i think he must have 300.  ((100+100) * 50%).
In other words, the percentage of attributes does not affect attributes from items. It acts only on the attributes that the character invests in each level. That is how it should be?

**Comment by DimasjkTV** [comment] 2019-10-16 23:30
I read. That was your idea. In which script can I change the formula a little?

**Comment by Callepo** [comment] 2019-10-17 19:13
item 100 x 0.5 = 50
100 + 50 = 150...
100 base int from character + 150 = 250

**Comment by DimasjkTV** [comment] 2019-10-17 19:18
> item 100 x 0.5 = 50
> 100 + 50 = 150...
> 100 base int from character + 150 = 250

and?I know this is in the game now. I want to find out where I can change the formula, so that the percentage is taken from all intelligence. Now the percentage is taken from the basic intelligence that you click on when investing attributes

**Comment by DimasjkTV** [comment] 2019-10-17 19:19
i need 100 + 100 + (100+100) * 0.5 = 300

**Comment by Callepo** [comment] 2019-10-17 19:20
things like this can be asked in discord cuase its not a bug or an issue with the kit, ill look into it and see if i can find

**Comment by DimasjkTV** [comment] 2019-10-17 19:22
I initially thought it was a bug. But then I read that it was the idea of the developer. I think there should be not only bugs here, but also any interaction with the developer

**Comment by Callepo** [comment] 2019-10-17 19:26
idk for sure hows its supposed to be but this area is called Issues which are bugs and problems thats why i said it, and some small things can be asked in the community thats all.. ur free to ask,

Ill try and find the formula for u

**Comment by DimasjkTV** [comment] 2019-10-17 19:50
U can close this!

**Comment by insthync** [comment] 2019-10-18 10:32
+Attribute %, is based on character attributes . 
for example, if character has 100 STR, then and equip item with +STR 5% (0.05)
Attribute will increase 100 * 5% = 100 * 0.05 = 5
So total attribute will be 105

**Comment by DimasjkTV** [comment] 2019-10-18 21:13
> +Attribute %, is based on character attributes .
> for example, if character has 100 STR, then and equip item with +STR 5% (0.05)
> Attribute will increase 100 * 5% = 100 * 0.05 = 5
> So total attribute will be 105

in which script i can remove the ability to use the skills that we get from items, but did not pump in the skills tree? For example, in the tree we have the “A” and “B” skill. “A” skill we pumped and put on an item with skill “B”. In the current situation, we can use both skills, but I want to make that we could not use skill “B”, since we did not put talent points in it.

If you need to change a lot of scripts, then I will refuse this. But if it’s enough to change some line, then why not

**Comment by DimasjkTV** [comment] 2019-10-22 00:29
> +Attribute %, is based on character attributes .
> for example, if character has 100 STR, then and equip item with +STR 5% (0.05)
> Attribute will increase 100 * 5% = 100 * 0.05 = 5
> So total attribute will be 105

how to remove crafting skills from this list?
![image](https://user-images.githubusercontent.com/47291794/67252555-25465880-f47c-11e9-8a37-2888bfe0d2b1.png)

**Comment by DimasjkTV** [comment] 2019-10-22 11:38
> +Attribute %, is based on character attributes .
> for example, if character has 100 STR, then and equip item with +STR 5% (0.05)
> Attribute will increase 100 * 5% = 100 * 0.05 = 5
> So total attribute will be 105

how to remove crafting skills from this list? 
![image](https://user-images.githubusercontent.com/47291794/67282083-90724800-f4d9-11e9-86f7-f789f3c2d067.png)

**Comment by insthync** [comment] 2019-10-22 13:49
> > +Attribute %, is based on character attributes .
> > for example, if character has 100 STR, then and equip item with +STR 5% (0.05)
> > Attribute will increase 100 * 5% = 100 * 0.05 = 5
> > So total attribute will be 105
> 
> how to remove crafting skills from this list?
> ![image](https://user-images.githubusercontent.com/47291794/67252555-25465880-f47c-11e9-8a37-2888bfe0d2b1.png)


I will add filter settings later, you may changes codes to not load crafting skills like this:
UICharacterHotkeyAssigner.cs - From Line 99
```
            foreach (KeyValuePair<BaseSkill, short> characterSkill in owningCharacter.GetCaches().Skills)
            {
                tempCharacterSkill = CharacterSkill.Create(characterSkill.Key, characterSkill.Value);
                if (uiCharacterHotkey.CanAssignCharacterSkill(tempCharacterSkill) && characterSkill.Key.GetSkillType() != SkillType.CraftItem) /* Add filter by item type condition */
                {
                    filterSkills.Add(tempCharacterSkill);
                    filterSkillsIndexes.Add(owningCharacter.IndexOfSkill(tempCharacterSkill.dataId));
                }
            }
```

**Comment by insthync** [comment] 2019-10-22 13:50
> > +Attribute %, is based on character attributes .
> > for example, if character has 100 STR, then and equip item with +STR 5% (0.05)
> > Attribute will increase 100 * 5% = 100 * 0.05 = 5
> > So total attribute will be 105
> 
> in which script i can remove the ability to use the skills that we get from items, but did not pump in the skills tree? For example, in the tree we have the “A” and “B” skill. “A” skill we pumped and put on an item with skill “B”. In the current situation, we can use both skills, but I want to make that we could not use skill “B”, since we did not put talent points in it.
> I want the skill bonus on the item not to allow use the skill that this item gives. First you need to pump this skill in the skill tree.
> maybe it will help to understand
> 
> If you need to change a lot of scripts, then I will refuse this. But if it’s enough to change some line, then why not

Add codes to `CanUse` function in `SkillExtension` class from line 60:
```
            // Check required skills
            Dictionary<BaseSkill, int> skillLevelsDict = new Dictionary<BaseSkill, int>();
            foreach (CharacterSkill learnedSkill in skillLearner.Skills)
            {
                if (learnedSkill.GetSkill() == null)
                    continue;
                skillLevelsDict[learnedSkill.GetSkill()] = learnedSkill.level;
            }
            foreach (BaseSkill requireSkill in skill.CacheRequireSkillLevels.Keys)
            {
                if (!skillLevelsDict.ContainsKey(requireSkill) ||
                    skillLevelsDict[requireSkill] < skill.CacheRequireSkillLevels[requireSkill])
                    return false;
            }
```
![Screenshot_123](https://user-images.githubusercontent.com/2697550/67291713-26bf6180-f50c-11e9-87ff-132e79c81d71.png)

**Comment by DimasjkTV** [comment] 2019-10-22 14:45
You can still apply the skills that the item gives, but which we have not learned
[20191022173337.zip](https://github.com/suriyun-production/mmorpg-kit-docs/files/3756323/20191022173337.zip)

**Comment by insthync** [comment] 2019-10-23 10:56
Add this at line 69
```
            if (!skillLevelsDict.ContainsKey(skill))
                return false;
```

![Screenshot_124](https://user-images.githubusercontent.com/2697550/67386067-7bbbb000-f5be-11e9-8dc6-f6a39520cc63.png)

But it might affect skill activate item so I will change condition when use skill activate item later

**Comment by insthync** [comment] 2019-10-23 11:02
Oh, it's actually can change all condition to
```
            bool skillLearned = false;
            Dictionary<BaseSkill, int> skillLevelsDict = new Dictionary<BaseSkill, int>();
            foreach (CharacterSkill learnedSkill in character.Skills)
            {
                if (learnedSkill.GetSkill() != null && learnedSkill.GetSkill() == skill)
                {
                    skillLearned = true;
                    break;
                }
            }
            if (!skillLearned)
                return false;
```
![Screenshot_125](https://user-images.githubusercontent.com/2697550/67386355-fe446f80-f5be-11e9-9417-e4c320b75018.png)

I think it has to changes codes in many places, it should not allow assigning to hotkey so I have to add condition when assigning to hotkey too.

**Comment by DimasjkTV** [comment] 2019-10-23 12:17
> Oh, it's actually can change all condition to
> 
> ```
>             bool skillLearned = false;
>             Dictionary<BaseSkill, int> skillLevelsDict = new Dictionary<BaseSkill, int>();
>             foreach (CharacterSkill learnedSkill in character.Skills)
>             {
>                 if (learnedSkill.GetSkill() != null && learnedSkill.GetSkill() == skill)
>                 {
>                     skillLearned = true;
>                     break;
>                 }
>             }
>             if (!skillLearned)
>                 return false;
> ```
> 
> ![Screenshot_125](https://user-images.githubusercontent.com/2697550/67386355-fe446f80-f5be-11e9-9417-e4c320b75018.png)
> 
> I think it has to changes codes in many places, it should not allow assigning to hotkey so I have to add condition when assigning to hotkey too.

**Comment by DimasjkTV** [comment] 2019-10-23 12:25
if you do not need this, then you can not redo it. The main thing that there were filters)

**Comment by DimasjkTV** [comment] 2019-10-26 09:26
> I think it has to changes codes in many places, it should not allow assigning to hotkey so I have to add condition when assigning to hotkey too.


Are you planning to add a button for breaking items into other items? For example, we can destroy a sword in order to get other resources.

**Comment by insthync** [comment] 2019-10-26 10:17
Does not planned yet, I think this is not hard to do :p

**Comment by Callepo** [comment] 2019-10-30 04:29
LOL, After begging for help for months.. u get mad at something that u didnt understand cuase u dont know english and block people? :) Ok kid XD

**Comment by Callepo** [comment] 2019-10-30 04:35
and pay fallen back for the asset he gave u for free if ur gonna block him :) 2d sprite studio ? remember?

**Comment by DimasjkTV** [comment] 2019-10-30 12:24
> LOL, After begging for help for months.. u get mad at something that u didnt understand cuase u dont know english and block people? :) Ok kid XD

Kindergarten. Calm down you already.

**Comment by insthync** [comment] 2019-10-30 12:44
What happen, did I do something wrong?

**Closed** 2019-10-30 14:02 UTC
