### ISSUE TITLE
Somethings wrong with controller in 1.76

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#1637] opened 2022-07-07 22:28 UTC
remember we had that already in older version
https://gyazo.com/72a47c12844c9f2d91dff8ac837ca8c8

**Comment by insthync** [comment] 2022-07-08 03:19
Fixed in 1.76b

**Closed by insthync** 2022-07-08 03:19 UTC

**Comment by moepi2k** [comment] 2022-07-08 08:35
still same issue in 176b
https://gyazo.com/d6fb821dab982ec18867bae4e65446b4

when use shooter controller combat mode. in view of other, character turning same as adventure mode.
only for owning player it works. seems state not update correctly

**Comment by insthync** [comment] 2022-07-08 10:12
From the first post, I thought the problem is animation, just realize that problem is rotation

**Comment by moepi2k** [comment] 2022-07-08 10:25
ohh, actually i didnt noticed any problem with animation from first video :P

**Comment by sdk2016** [comment] 2022-07-08 17:15
I think the problem is not animation. Because this is happen after updating the kit to 176. Would you like to recheck it? Thankyou.

**Comment by insthync** [comment] 2022-07-08 17:58
@sdk2016 NO :)

**Comment by insthync** [comment] 2022-07-08 19:34
Fixed in 1.76c

**Comment by insthync** [comment] 2022-07-09 04:28
Try 1.76c2
