### ISSUE TITLE
IOS Skill not showing

### ISSUE THREAD

**Issue by john5514** [suriyun-production/mmorpg-kit-docs#2406] opened 2024-02-06 03:32 UTC
When I switched the app to IOS, my skills stopped showing

I checked on the game database side, everything is entered correctly, maybe the loop system is not working, I put them all in the loop, again the same way, the skills do not appear.

the FXs of the skils are not visible, when I press it, it doesn't summon. 

but when you enter the skils one by one, they all work fine

**Comment by insthync** [comment] 2024-02-06 03:37
Is it a offline game or MMO game?

**Comment by john5514** [comment] 2024-02-06 03:38
MMO Game online

**Comment by insthync** [comment] 2024-02-06 03:43
I actually not sure what is a switch meaning, switch between apps on iPhone/iPad? or you just want to tell me that you are working on iOS game development?.

The problem is it can connect to server but it has no skills ?

Can you debug it with XCode and try find an error from its debug console ?

**Comment by john5514** [comment] 2024-02-06 03:45
I made IOS platform switch from windows or android part of the project on unity

on the editor side there are no FXs of skils on the iphone or ipad side at all

The only thing that gave a warning on the xcode side was the unity purchase, otherwise there are no errors.

Yes, it connects to the server, but the skills work, you press it and it plays the animation, but the fx and particle effects that come with it do not work.

**Comment by insthync** [comment] 2024-02-06 03:53
So problems is: an fx/particle effects are not playing, but skill can be applied so it can attack enemy or buffs (or etc) but it don't having an fx/particle effects, that is it?

**Comment by john5514** [comment] 2024-02-06 04:05
Yes truely

its example video


https://github.com/suriyun-production/mmorpg-kit-docs/assets/145167928/674632c7-a553-4a8d-b9ce-0ea448e0a8a3

**Comment by john5514** [comment] 2024-02-09 12:19
@insthync i try switch android not fx not show It doesn't show up completely, it doesn't show up on android anymore.

**Comment by shubhank008** [comment] 2024-02-10 23:01
> Yes truely
> 
> its example video
> 
>  recording-2024-02-06-07-04-22.mp4

1. Whatever particle effect/Vfx you are using, check separately if it renders in editor, like drag-drop in scene and try to play the effect. It might be possible due to a shader/material issue.
2. In editor, during play, you can search in your scene hierarchy for the particle effect's gameobject, if it was pre-instantiated. It should be in disabled state and when you use skill, it should enable (even if it doesnt show). 
That would confirm atleast the prefabs are setup correctly and working and its a visual glitch
3. Try to switch build target to windows and check if it works

I am building for mobile as well and the Vfx/Spells work fine.

**Comment by john5514** [comment] 2024-02-13 15:53
> 

I also know that everything was working very well in the broadcast of our application, when we switched to ios, everything was a problem, I think it was because of the jamming method. 

and not worked sir @shubhank008 @insthync

**Comment by insthync** [comment] 2024-02-20 05:01
May I try on your device by AnyDesk?

**Comment by insthync** [comment] 2024-03-02 20:25
No answer, so I determined that you do not need help anymore, so I will close this.

**Closed by insthync** 2024-03-02 20:25 UTC
