### ISSUE TITLE
Mysql error, player cant login anymore

### ISSUE THREAD

**Issue by moepi2k** [suriyun-production/mmorpg-kit-docs#2586] opened 2024-10-22 20:43 UTC
i had this issue few years ago already. player cant login anymore even after restart server. it stuck after selecting character. last time i remember there was an issue with an equipet item or so. but i thought it was fixed.

this is the error log:

ERROR DatabaseNetworkManager [2024-10-22 22:17:45] - Cannot UpdateUserCount status: Timeout
ERROR No Tag [2024-10-22 22:17:53] - OverflowException: Arithmetic operation resulted in an overflow.
MySqlConnector.Core.ResultSet.<ScanRowAsync>g__ScanRowAsyncRemainder|9_1 (MySqlConnector.Core.ResultSet resultSet, MySqlConnector.Protocol.PayloadData payload, MySqlConnector.Core.Row row) (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/Core/ResultSet.cs:316)
MySqlConnector.Core.ResultSet.ScanRowAsync (MySqlConnector.Protocol.Serialization.IOBehavior ioBehavior, MySqlConnector.Core.Row row, System.Threading.CancellationToken cancellationToken) (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/Core/ResultSet.cs:236)
MySqlConnector.Core.ResultSet.ReadAsync (MySqlConnector.Protocol.Serialization.IOBehavior ioBehavior, System.Threading.CancellationToken cancellationToken) (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/Core/ResultSet.cs:200)
MySqlConnector.Core.ResultSet.Read () (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/Core/ResultSet.cs:192)
MySqlConnector.MySqlDataReader.Read () (at D:/Projects/CSharp/MySqlConnector-1.3.11/src/MySqlConnector/MySqlDataReader.cs:34)
MultiplayerARPG.MMO.MySQLDatabase.ReadStorageItem (MySqlConnector.MySqlDataReader reader, MultiplayerARPG.CharacterItem& result) (at <dfb94e1b3f994189a3fb1846b7dbfafc>:0)
MultiplayerARPG.MMO.MySQLDatabase+<>c__DisplayClass171_0.<ReadStorageItems>b__0 (MySqlConnector.MySqlDataReader reader) (at <dfb94e1b3f994189a3fb1846b7dbfafc>:0)
MultiplayerARPG.MMO.MySQLDatabase.ExecuteReader (MySqlConnector.MySqlConnection connection, MySqlConnector.MySqlTransaction transaction, System.Action`1[T] onRead, System.Boolean isAsync, System.String sql, MySqlConnector.MySqlParameter[] args) (at <dfb94e1b3f994189a3fb1846b7dbfafc>:0)
Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) (at <45b7092461144f998a40a36a425ccaa5>:0)
MultiplayerARPG.MMO.MySQLDatabase.ExecuteReader (MySqlConnector.MySqlConnection connection, MySqlConnector.MySqlTransaction transaction, System.Action`1[T] onRead, System.String sql, MySqlConnector.MySqlParameter[] args) (at <dfb94e1b3f994189a3fb1846b7dbfafc>:0)
Cysharp.Threading.Tasks.UniTask+ExceptionResultSource.GetResult (System.Int16 token) (at <45b7092461144f998a40a36a425ccaa5>:0)
MultiplayerARPG.MMO.MySQLDatabase.ExecuteReader (System.Action`1[T] onRead, System.String sql, MySqlConnector.MySqlParameter[] args) (at <dfb94e1b3f994189a3fb1846b7dbfafc>:0)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1[TStateMachine].GetResult (System.Int16 token) (at <45b7092461144f998a40a36a425ccaa5>:0)
MultiplayerARPG.MMO.MySQLDatabase.ReadStorageItems (MultiplayerARPG.StorageType storageType, System.String storageOwnerId) (at <dfb94e1b3f994189a3fb1846b7dbfafc>:0)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) (at <45b7092461144f998a40a36a425ccaa5>:0)
MultiplayerARPG.MMO.DatabaseNetworkManager.ReadStorageItems (MultiplayerARPG.StorageType storageType, System.String storageOwnerId) (at <dfb94e1b3f994189a3fb1846b7dbfafc>:0)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) (at <45b7092461144f998a40a36a425ccaa5>:0)
MultiplayerARPG.MMO.DatabaseNetworkManager.ReadStorageItems (LiteNetLibManager.RequestHandlerData requestHandler, MultiplayerARPG.MMO.ReadStorageItemsReq request, LiteNetLibManager.RequestProceedResultDelegate`1[TResponse] result) (at <dfb94e1b3f994189a3fb1846b7dbfafc>:0)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception)
MultiplayerARPG.MMO.<ReadStorageItems>d__87:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run()
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:SetException(Exception)
MultiplayerARPG.MMO.<ReadStorageItems>d__126:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run()
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:SetException(Exception)
MultiplayerARPG.MMO.<ReadStorageItems>d__171:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2:Run()
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetException(Exception)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetException(Exception)
MultiplayerARPG.MMO.<ExecuteReader>d__20:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run()
Cysharp.Threading.Tasks.AwaiterActions:Continuation(Object)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1:TrySetResult(AsyncUnit)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:SetResult()
MultiplayerARPG.MMO.<OpenConnection>d__10:MoveNext()
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`1:Run()
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

any ideas?

**Comment by insthync** [comment] 2024-10-22 21:30
My answer might be a stupid answer, so I don't want to answer :)

**Comment by insthync** [comment] 2024-10-22 21:48
As I read the error, I think the problem is it read wrong type of data, your column type in your table struct might be different to the reader codes.

For example if your table have following columns: id (string), dataId (int), level(short), amount(short)

but your reader read it as string, int, int, int then the error occurs

**Comment by moepi2k** [comment] 2024-10-22 23:00
so the table import is vanilla from 188f5 nothning changed and no custom tables/colums.
so yea need to check where or why it happen then

**Comment by insthync** [comment] 2024-10-22 23:06
"Vanilla" :)

**Comment by moepi2k** [comment] 2024-10-23 15:46
I mean default. Nothing custom

**Comment by moepi2k** [comment] 2024-10-23 20:55
just to let u know
https://gyazo.com/df4dcadd6246032dc0067e4360175fa4
the marked entry caused the issue so player was not able to login. its just a normal item evey other player has. so dont know why it cause that issue.

**Comment by insthync** [comment] 2024-10-24 01:32
then it might be a mysqlconnector's issues? which i won't going to fix it, you may try use my .net version of database management to find if it is because of mysqlconnector or not, but you must find the correct version for your project

**Comment by insthync** [comment] 2024-10-24 03:23
or you may export that character data to me to test, just one character which having an issues

**Comment by moepi2k** [comment] 2024-10-24 06:42
email?

**Comment by insthync** [comment] 2024-10-24 06:56
Yes

**Comment by insthync** [comment] 2024-10-24 18:50
Yep, it is MySQLConnector bug which it cannot read the `522328318` and I can't fix it, You may try following choices:
- Try find a MySQLConnector version which work for your project.
- Use [this](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_MMO.NET) or [this](https://github.com/suriyun-mmorpg/UnityMultiplayerARPG_DatabaseManager) instead.
- Change item ID.

**Comment by insthync** [comment] 2024-10-24 19:19
You also can change value type to varchar (it work)

**Comment by moepi2k** [comment] 2024-10-24 19:27
what do you prefer of those above? and do you mean change varchar for storageitem and characteritem to from int to varchar? 
https://gyazo.com/e379117e27ec7c3ac723737a175fed95

**Comment by insthync** [comment] 2024-10-24 19:31
I prefer to use .NET version of database management web service

**Comment by insthync** [comment] 2024-10-24 19:31
Yes. change data ID to varchar

**Comment by insthync** [comment] 2024-10-24 19:32
Any more bugs that you've told I won't fix ?

**Comment by moepi2k** [comment] 2024-10-24 19:32
yes but i better will mail it to you

**Comment by insthync** [comment] 2024-10-24 19:33
Why?

**Comment by insthync** [comment] 2024-10-24 19:35
So you have never reported that bug and told me I won't fix bugs?

**Comment by moepi2k** [comment] 2024-10-24 19:36
here another one -> 
![image](https://github.com/user-attachments/assets/19dd108b-0fd2-4389-86ca-590ef99a1113)
sometimes player get locked out and get this message, no way the enter game until you restart seerver

**Comment by insthync** [comment] 2024-10-24 19:37
This one too, you never report me, why did you told me I won't fix bugs?

**Comment by insthync** [comment] 2024-10-24 19:41
Then just try to reopen it or repost it, not blaming me that I won't fix

**Comment by moepi2k** [comment] 2024-10-24 19:43
calm down please, okey, we just discusse and i try to help u find bugs, ok?

**Comment by insthync** [comment] 2024-10-24 19:45
I won't okay if anyone makes up the story like you did

**Comment by insthync** [comment] 2024-10-24 19:47
Any more bugs ?

**Comment by moepi2k** [comment] 2024-10-24 19:51
yes. instanced dungeon after some time lead to crash mapserver. everytime the player join it starts then player get msg rejected and server closed and kick out of game. then need to restart game and player will stay on normal map (warpportal)

https://gyazo.com/e2c925553c9d0af0e3e59d8ff45a90eb

this is something i not tested yet with default kit so dont know if its maybe something on my side

**Comment by insthync** [comment] 2024-10-24 19:52
Post all bugs you've found

**Comment by moepi2k** [comment] 2024-10-24 19:54
[player report https://github.com/suriyun-production/mmorpg-kit-docs/issues/1756](https://github.com/suriyun-production/mmorpg-kit-docs/issues/1756)

same issue. player report rarely that pets level reset to 1 while playing

**Comment by insthync** [comment] 2024-10-24 20:00
I will sleep now, I hope I will see it have as many as you've told me, and I won't know why you choose to blame me instead of creating bug reporting.

**Comment by moepi2k** [comment] 2024-10-24 20:10
you see what i do? reproting bugs xD and i dont blame you. i always wanted to help you. why i else should report so many bugs?

btw just was able to reproduce pet level reseting. sometimes happen when u have a pet with specific level in inventory and u add another pet of the same type it will reset. in my case i added it with /add_item PET

**Comment by insthync** [comment] 2024-10-24 20:13
And... I don't fix bugs as you said?

**Comment by RunOrDi3** [comment] 2024-10-24 22:25
Calm down guys , first thanks to @insthync for fixing bugs , second @moepi2k  report all the bugs you found every bug in a single post and @insthync will fix them .. thats all

**Comment by insthync** [comment] 2024-10-25 04:36
@RunOrDi3 Yep, if he just reports bugs before blaming me then I won't have problems.

**Comment by moepi2k** [comment] 2024-10-25 06:10
Ok so for the pet thing. One guy just reportet that the pet even disappeard when the player died while using pet. Sonseems there are multible issues with pet

**Comment by insthync** [comment] 2024-10-25 06:43
Any other bugs that not relate to pet?

**Closed** 2024-10-25 21:51 UTC

**Comment by insthync** [comment] 2024-10-26 10:06
Hey, repost or comment whats you've commented here that is not related to the title to others.
