### ISSUE TITLE
[BUG]: Surface Swimming Bug

### ISSUE THREAD

**Issue by BJPickles** [suriyun-production/mmorpg-kit-docs#2269] opened 2023-10-01 11:10 UTC
Tested in 1.85b3 today. Whenever a character swims on the surface, or has "auto swim to surface" enabled, the following occurs:
https://i.imgur.com/39kFJjL.mp4

## Suggested fix
1. Have "Surface swimming" animations.
2. Have "Underwater swimming" animations.

- Lock player to the surface, disabling Y axis when swimming.
- Have a separate "dive" button which pushes character underwater.
- After pressing dive button, enable Y axis controls for underwater swimming. (Space UP / Ctrl Down). 
- **Underwater Video example**: https://i.imgur.com/SGEL4YP.mp4
- **Surface Video example**: https://i.imgur.com/Hmw8q4z.mp4 (Locked to surface)

**Comment by insthync** [comment] 2023-10-01 11:40
Better fix it and then share codes with me :)

**Comment by insthync** [comment] 2023-10-22 20:39
I want to decline your suggestion, it is not just a bug fixing, it is adding more features and can be the cause of other bugs.

**Comment by insthync** [comment] 2023-10-22 20:56
Did you use root motion for underwater movement ?

**Comment by BJPickles** [comment] 2023-10-22 21:06
> I want to decline your suggestion, it is not just a bug fixing, it is adding more features and can be the cause of other bugs.

That's fine Suri :)
It was just a suggestion, I don't want to cause you unnecessary work.



> Did you use root motion for underwater movement ?

No, this is CC controller. Auto-swim to surface. In-place animations.

**Comment by insthync** [comment] 2023-10-22 21:08
I fix it by doing it like this
```
// It will be called in LateUpdate
        public void FixSwimUpPosition(float deltaTime)
        {
            if (!CanPredictMovement())
                return;

            if (_isUnderWater)
            {
                Vector3 tempTargetPosition = Vector3.up * (_waterCollider.bounds.max.y - (EntityMovement.GetBounds().size.y * underWaterThreshold));
                if (CacheTransform.position.y > tempTargetPosition.y)
                    CacheTransform.position = new Vector3(CacheTransform.position.x, tempTargetPosition.y, CacheTransform.position.z);
            }
        }

```

I will publish a new version in a few minute

**Comment by BJPickles** [comment] 2023-10-22 21:09
> Did you use root motion for underwater movement ?

Sorry, I misunderstood. In this video https://i.imgur.com/SGEL4YP.mp4 they are root motion animations. It is from MalberS Animal Controller.

**Comment by BJPickles** [comment] 2023-10-22 21:09
> I fix it by doing it like this
> 
> ```
> // It will be called in LateUpdate
>         public void FixSwimUpPosition(float deltaTime)
>         {
>             if (!CanPredictMovement())
>                 return;
> 
>             if (_isUnderWater)
>             {
>                 Vector3 tempTargetPosition = Vector3.up * (_waterCollider.bounds.max.y - (EntityMovement.GetBounds().size.y * underWaterThreshold));
>                 if (CacheTransform.position.y > tempTargetPosition.y)
>                     CacheTransform.position = new Vector3(CacheTransform.position.x, tempTargetPosition.y, CacheTransform.position.z);
>             }
>         }
> ```
> 
> I will publish a new version in a few minute

I'll give this a go in a moment :)

**Comment by insthync** [comment] 2023-10-22 21:16
Uploaded

**Comment by BJPickles** [comment] 2023-10-24 17:53
Sadly this hasn't fixed it - and interestingly when you type in chat, it seems to idle _more_, but when you stop chatting it doesn't.

**Comment by insthync** [comment] 2023-10-24 17:57
How ?

**Comment by BJPickles** [comment] 2023-10-24 17:58
Let me get a video one sec

**Comment by BJPickles** [comment] 2023-10-24 18:01
This is Male CC. Animations are baked in place.

https://i.imgur.com/7hSG6Qq.mp4

**Comment by insthync** [comment] 2023-10-24 18:09
What is the bug?

In this post, you talked about the position

Then this one is movement state, is it the same thing?

The position bugs were fixed or not?

Very confusing.

**Comment by BJPickles** [comment] 2023-10-24 18:32
My apologies if my words were confusing and I didn't make myself clear.

When player stops swimming forward, idle animation should play. 
So the bug = when the player is idle (and swimming), it constantly switches between idle and swim forward: https://imgur.com/39kFJjL

Expected behaviour:
- Idle = swim idle animation
- Swim forward = Swim forward animation plays.

This is when auto-swim to surface is enabled.


My suggestion was to separate surface and underwater swimming if the idle issue was persisting.

**Comment by insthync** [comment] 2023-10-24 18:35
How about position bugs?

This one is not about position? (https://imgur.com/39kFJjL)

**Comment by insthync** [comment] 2023-10-24 18:39
So the problem is just animation, why didn't you tell me what an actual problem is, and what you've suggested to me is to fix position bugs, isn't it?

If it is because of animation it is simply fixed by adding some duration or distance to detect movement, not having to add surface things.

**Comment by BJPickles** [comment] 2023-10-24 19:11
Yeah my bad, sorry Suri. I thought the bug was self explanatory from the video, but next time I'll take more care to explain it

**Comment by insthync** [comment] 2023-10-24 20:09
![Screenshot_897](https://github.com/suriyun-production/mmorpg-kit-docs/assets/2697550/1d9745e5-d15e-4118-ad34-a72f0aac122e)

Add this line to fix it.

**Closed by insthync** 2023-10-24 20:09 UTC
