### ISSUE TITLE
Instanced Warping

### ISSUE THREAD

**Issue by Callepo** [suriyun-production/mmorpg-kit-docs#648] opened 2020-10-20 20:12 UTC
Warping from npc to an instanced map is still bugged.
You will get Warping message and get stuck there till u dc.
other people have this issue too.

**Comment by insthync** [comment] 2020-10-20 20:34
Not sure that map loading done or not, You may test with server config `notSpawnInBatchMode` set to `false`.

**Comment by Callepo** [comment] 2020-10-20 20:39
ok i will

**Comment by moepi2k** [comment] 2020-10-21 06:36
I also noticed when use a portal to warp to an instance , the smalll white loading window lasts longer than when us warp to normal scene, for eg 5 seconds, during this time you can still walk around

**Comment by Callepo** [comment] 2020-10-21 11:57
thats normal .. its looking for party members.. and it has a timer set for that

**Comment by moepi2k** [comment] 2020-10-21 13:16
alright thank you

**Comment by Callepo** [comment] 2020-10-24 00:13
@insthync No effect.. Still dc 
still no working Batchmode = false

**Comment by ollisan05** [comment] 2020-10-24 15:53
I can confirm still getting DC'd, tried everything, even the notSpawnInBatchMode = false

**Comment by insthync** [comment] 2020-10-26 07:56
It may be because it takes so long time to load map then it's timed out before map loaded

**Comment by insthync** [comment] 2020-10-26 08:06
I will make it no timing out  for spawn map messages.

**Comment by ollisan05** [comment] 2020-11-02 23:05
Sounds good 👍

**Comment by insthync** [comment] 2020-11-05 02:31
Try 1.60

**Comment by Callepo** [comment] 2020-11-05 02:41
This is simply amazing.. holy shit..

**Comment by ollisan05** [comment] 2020-11-08 18:51
For me i can still not get into instanced map, on mmo server you can only teleport between for example Map001 and Map002, but I added a Map003 copy of Map002 and added a teleporter for it, It warps and then camera gets removed from scene and you are still in Map001 (latest update fresh project)

**Comment by insthync** [comment] 2020-11-08 18:54
Did you create map info and add to game database yet ?

**Comment by ollisan05** [comment] 2020-11-08 18:56
Yes sir i did

**Comment by insthync** [comment] 2020-11-08 18:57
There is no error in any log files ?

**Comment by ollisan05** [comment] 2020-11-08 18:59
[Log_Database_Central_Chat_MapSpawn.txt](https://github.com/suriyun-production/mmorpg-kit-docs/files/5506993/Log_Database_Central_Chat_MapSpawn.txt)

**Comment by ollisan05** [comment] 2020-11-08 18:59
[Log_Map(Map003) Instance().txt](https://github.com/suriyun-production/mmorpg-kit-docs/files/5506994/Log_Map.Map003.Instance.txt)

**Comment by insthync** [comment] 2020-11-08 19:22
Hmmm, no errors in the logs.

**Comment by ollisan05** [comment] 2020-11-08 19:23
Callepo said that i probably haven't opened the ports other than 8000 and 8001 which is most likely true so i will allow 8002 and see if that works!

**Comment by ollisan05** [comment] 2020-11-08 19:29
omg i feel so stupid, i can confirm that this issue is now fixed works totally fine now!! :D Awesome job Insthync!

I just forgot to add ports for the new maps.

**Comment by Callepo** [comment] 2020-11-08 21:18
@insthync its solved XD

**Closed** 2020-11-11 07:39 UTC
