### ISSUE TITLE
Warning in Play mode when monster attacks

### ISSUE THREAD

**Issue by Eniotnacram** [suriyun-production/mmorpg-kit-docs#2036] opened 2023-04-23 05:42 UTC
Hello, when in play mode, im getting this warning when my monsters attack

"Physics.ClosestPoint can only be used with a BoxCollider, SphereCollider, CapsuleCollider and a convex MeshCollider.
UnityEngine.Collider:ClosestPoint (UnityEngine.Vector3)"

But it is not simply a warning, my monsters now attack themselves when attacking. The "Impact Effect" activates on them.

Using Version 1.82c5.

Im not the only one having this problem as we talked about it on discord.

Let me know if you need more info :)

**Comment by insthync** [comment] 2023-04-23 06:01
Which kind of attacking?

**Comment by insthync** [comment] 2023-04-23 07:52
Melee, Range, Raycast, Throwable?

**Comment by insthync** [comment] 2023-04-23 09:58
I can't find where I've used `Physics.ClosestPoint` function, I guess it may be a part of any other physic functions, so please include full log messages

**Comment by khongtuong** [comment] 2023-04-23 11:35
melee attack type impact effect activated on self if no target, projectile collide with self and bounce to no where not target direction

`Physics.ClosestPoint can only be used with a BoxCollider, SphereCollider, CapsuleCollider and a convex MeshCollider.
UnityEngine.Collider:ClosestPoint (UnityEngine.Vector3)
MultiplayerARPG.PhysicFunctions:GetOverlapColliderClosestPoint (int,UnityEngine.Vector3) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/PhysicFunctions/PhysicFunctions.cs:124)
MultiplayerARPG.DamageInfo:LaunchMeleeDamage (MultiplayerARPG.BaseCharacterEntity,bool,MultiplayerARPG.CharacterItem,System.Collections.Generic.Dictionary`2<MultiplayerARPG.DamageElement, MinMaxFloat>,MultiplayerARPG.BaseSkill,int,int,MultiplayerARPG.AimPosition,UnityEngine.Vector3,System.Collections.Generic.Dictionary`2<uint, int>&) (at Assets/UnityMultiplayerARPG/Core/Scripts/GameData/Damage/Damage.cs:307)
MultiplayerARPG.DamageInfo:LaunchDamageEntity (MultiplayerARPG.BaseCharacterEntity,bool,MultiplayerARPG.CharacterItem,System.Collections.Generic.Dictionary`2<MultiplayerARPG.DamageElement, MinMaxFloat>,MultiplayerARPG.BaseSkill,int,int,MultiplayerARPG.AimPosition,UnityEngine.Vector3,System.Collections.Generic.Dictionary`2<uint, int>&) (at Assets/UnityMultiplayerARPG/Core/Scripts/GameData/Damage/Damage.cs:213)
MultiplayerARPG.DefaultCharacterAttackComponent:ApplyAttack (bool,MultiplayerARPG.CharacterItem,MultiplayerARPG.DamageInfo,System.Collections.Generic.Dictionary`2<MultiplayerARPG.DamageElement, MinMaxFloat>,MultiplayerARPG.AimPosition,int) (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterSystems/CharacterActionsSystem/DefaultCharacterAttackComponent.cs:306)
MultiplayerARPG.DefaultCharacterAttackComponent/<AttackRoutine>d__48:MoveNext () (at Assets/UnityMultiplayerARPG/Core/Scripts/Gameplay/CharacterSystems/CharacterActionsSystem/DefaultCharacterAttackComponent.cs:222)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1<MultiplayerARPG.DefaultCharacterAttackComponent/<AttackRoutine>d__48>:Run () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/StateMachineRunner.cs:104)
Cysharp.Threading.Tasks.AwaiterActions:Continuation (object) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTask.cs:21)
Cysharp.Threading.Tasks.UniTaskCompletionSourceCore`1<object>:TrySetResult (object) (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTaskCompletionSource.cs:139)
Cysharp.Threading.Tasks.UniTask/DelayIgnoreTimeScalePromise:MoveNext () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/UniTask.Delay.cs:796)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:RunCore () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs:175)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Update () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs:145)
Cysharp.Threading.Tasks.Internal.PlayerLoopRunner:Run () (at Assets/UnityMultiplayerARPG/Core/LiteNetLibManager/Plugins/UniTask/Runtime/Internal/PlayerLoopRunner.cs:104)`

**Comment by insthync** [comment] 2023-04-23 12:27
Projectile is raycast or missile damage entity?

**Comment by khongtuong** [comment] 2023-04-23 12:55
> Projectile is raycast or missile damage entity?

Projectile missile dmg entity

**Comment by insthync** [comment] 2023-04-23 12:57
`ProjectileDamageEntity` ?

**Comment by Eniotnacram** [comment] 2023-04-23 12:58
For me it does with with melee attack. My monsters only have melee

**Comment by khongtuong** [comment] 2023-04-23 13:16
> ProjectileDamageEntity

yes

**Comment by insthync** [comment] 2023-04-23 13:27
@khongtuong, you character's entity movement is RigidbodyEntityMovement right?

**Comment by khongtuong** [comment] 2023-04-23 13:34
> @khongtuong, you character's entity movement is RigidbodyEntityMovement right?

CharacterControllerEntityMovement

**Comment by insthync** [comment] 2023-04-23 13:37
@khongtuong how about your monster character's entity movement?

**Comment by khongtuong** [comment] 2023-04-23 13:41
> @khongtuong how about your monster character's entity movement?

i'm using navmesh entity movement and CharacterControllerEntityMovement

**Comment by insthync** [comment] 2023-04-23 13:48
So for melee, the issue is just effect playing, damage not being applied, right?

**Comment by khongtuong** [comment] 2023-04-23 14:01
- For melee: effect applied on self and target, damage applied. 
- For missile: if using missile dmg entity it's work ok, but if using projectile dmg entity it's collider itself and dmg not applied.

**Comment by insthync** [comment] 2023-04-23 14:03
Damage appiled to self?

**Comment by khongtuong** [comment] 2023-04-23 14:05
> 

ah, only effect, dmg not applied to self

**Comment by Eniotnacram** [comment] 2023-04-23 14:13
I'm using rigid body entity movement for player and navmesh for monsters. No damage applied when melee, only impact effect

**Comment by Eniotnacram** [comment] 2023-04-23 18:42
Let me know if you need more information again :)

**Comment by Eniotnacram** [comment] 2023-04-24 17:15
There a video to help you understand the problem visually. 
https://medal.tv/games/requested/clips/16hhDlrFKkPh-C/d13372QvrMc0?invite=cr-MSxnd2gsNDQ3NDMxODYs

**Comment by insthync** [comment] 2023-04-24 23:15
Fixed in 1.82d

**Closed by insthync** 2023-04-24 23:15 UTC
