### ISSUE TITLE
Conection rejected by server each first login time 

### ISSUE THREAD

**Issue by MosesGomez** [suriyun-production/mmorpg-kit-docs#1485] opened 2022-02-28 20:42 UTC
Hello. Sorry to bother but I have this bug, cant really tell whats happening

https://www.youtube.com/watch?v=Q3RFWNEbX-8

**Comment by insthync** [comment] 2022-03-02 03:00
How about your current networking system? WebGL + Secure WebSocket?

**Comment by MosesGomez** [comment] 2022-03-02 03:07
> How about your current networking system? WebGL + Secure WebSocket?

I havent been able to fix the secure websocket yet

**Comment by insthync** [comment] 2022-03-02 04:09
Is it occurring frequently?

About secure websocket, You may register for the domain and use letsencrypt which is free SSL.

**Comment by insthync** [comment] 2022-03-02 04:36
Only first login ?, first when launch the client and connect or first when run the server and first client connect?

**Comment by MosesGomez** [comment] 2022-03-02 20:17
![image](https://user-images.githubusercontent.com/12781104/156442569-57474d56-0354-47d2-95d5-65fa55bfd8a0.png)
Just as heads up, I think this is the error.

**Comment by Reinhartdelille** [comment] 2022-03-28 15:24
Hi guys

I actually have the same problem, in Unity editor connecting to websocket goes immediately (when you are in Character Selection and press start), When hosted on WebGL, the first time it's refused, you go back to the login screen, you select the character and it works.

![image](https://user-images.githubusercontent.com/19047081/160432099-ad49d830-2d44-4f01-85b0-7236915b566b.png)

**Comment by Reinhartdelille** [comment] 2022-03-29 12:01
I think the problem is here, you moved the websocket to the new Netcore Server implementation. 

Now, in WebGL probably we must then also create the websocket connection async just like in the WSSTransportclient, as now it might return immediately and thus will be viewed as not connecting? @insthync ?

![image](https://user-images.githubusercontent.com/19047081/160606356-663bdf67-997f-4b68-81e2-a00608d19802.png)

**Comment by insthync** [comment] 2022-03-29 22:24
No, that is not cause of problem, you can notice that it is in non-webgl condition.

I found the cause of problem, it's because in the WebGL plugin(.jslib) when start connection first ID is `0`, so when we are going to check connection state later with difference instance of `WsClientWrapper` it will use wrong ID.

To fix it, just change codes in `WsClientWrapper` line `40` to `private int wsNativeInstance = -1;`

**Comment by Reinhartdelille** [comment] 2022-03-30 09:08
Senpai, this worked perfectly, thank you !

**Comment by insthync** [comment] 2022-04-19 05:57
Fixed in 1.74

**Closed by insthync** 2022-04-19 05:57 UTC
